### ISSUE TITLE
Training Bias Model doubts and Memory Usage error in Model Training

### ISSUE THREAD

**Issue by Rafaelsoler13** [kundajelab/chrombpnet#102]
Hello,

I have been trying to train a model with ChromBPnet. I created my own training bias model and I have a few questions for two topics:

1) Training Bias Model

After training my custome bias model, I obtained the overall_report.html. In this file, my bias model pass all the thresholds related with the pearsonr or jds, but for TFModisco motifs generated from profile contribution scores, I obtained some results that created some doubts. 

1.1) The top 9 motifs learnt are all transposases, except for one TF motif with the qval of 1 (not relevant). However, between the position 10 and 15, there are some CTCF motifs with a qvalue <1e-06. Is that problematic?

1.2) In the motifs generated from counts contribution, I have more TFs, being the qval between 1e-02 - 1e-04. I have tried to reduce the bias_threshold_factor, but then my pearsonr in peaks is less than -0.3 (-0.43), and it learns GC like motifs. What would be the best option? Keep the 0.5 or 0.4, or train the bias model with more data?

2) Training Model memory usage

I have tried to train the model with this previous trining bias model, but it gives me this error due to memory problems:

```
 Stats: 
Limit:                      4885184512
InUse:                      4884900864
MaxInUse:                   4885168128
NumAllocs:                      694819
MaxAllocSize:               3296334848
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2023-04-21 01:52:58.093963: W tensorflow/core/common_runtime/bfc_allocator.cc:474] ****************************************************************************************************
2023-04-21 01:52:58.093991: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:138 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[32,2090,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "~/anaconda3/envs/chrombpnet2/bin/chrombpnet", line 8, in <module>


.......
.......
.......


~/anaconda3/envs/chrombpnet2/lib/python3.8/site-packages/keras/layers/convolutional.py", line 3428, in call
      return inputs[:, self.cropping[0]:-self.cropping[1], :]
Node: 'model/bpnet_1crop/strided_slice'
OOM when allocating tensor with shape[32,2090,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/bpnet_1crop/strided_slice}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_predict_function_23175]
```

I have tried to reduce the batch size with _-bs 1_ but it gives me the same error:

```

Limit:                      4885184512
InUse:                      4884900864
MaxInUse:                   4885168128
NumAllocs:                     3158399
MaxAllocSize:               3296334848
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2023-04-20 23:14:49.606310: W tensorflow/core/common_runtime/bfc_allocator.cc:474] ****************************************************************************************************
2023-04-20 23:14:49.606341: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at strided_slice_op.cc:138 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[32,2090,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "~/anaconda3/envs/chrombpnet2/bin/chrombpnet", line 8, in <module>
    sys.exit(main())


.......
.......
.......


    File "~/anaconda3/envs/chrombpnet2/lib/python3.8/site-packages/keras/layers/convolutional.py", line 3428, in call
      return inputs[:, self.cropping[0]:-self.cropping[1], :]
Node: 'model/bpnet_1crop/strided_slice'
OOM when allocating tensor with shape[32,2090,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/bpnet_1crop/strided_slice}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_predict_function_344826]
```

Is there a solution to train the model with less memory despite having to wait longer?

Thank you so much for everything!

Rafael

**Comment by panushri25** [comment]
Hello Rafael,

Thanks for your questions. 

(1.1 and 1.2) Can you share the reports for both the thresholds here, I can help take a look and confirm? Sometimes the q-values are lower but the motifs really dont match the TF motif, I just want to make sure this is not the case. 

(2) You can try to reduce your batch size to train it on the same gpu and see if it fits in the memory. 

Best, 
Anu

**Comment by Rafaelsoler13** [comment]
Yes! Here they are

With -b 0.5
[IPSC_overall_report.pdf](https://github.com/kundajelab/chrombpnet/files/11313036/IPSC_overall_report.pdf)

With -b 0.4
[IPSC_overall_report.pdf](https://github.com/kundajelab/chrombpnet/files/11313045/IPSC_overall_report.pdf)

I tried to reduce the batch size to -bs 1, but it is still appearing this error message.

**Comment by panushri25** [comment]
There is still a CTCF motif in your `0.4` threshold. Can you retrain a bias model using 0.5 threshold but this time 
input only half the non-peaks from train/validation tests while keeping the test set same. 

So for example if for a human model I am training a bias model for fold 0, I would keep the rows with    "chr1",  "chr3",  "chr6" intact in the non-peaks bed file. And randomly subsample the remaining rows to 50% and 80% and make 2 sets of bed file. I would then try training a bias model on each of these sets. If at 80% data I am able to train a bias model without capturing any TF motifs I would give that priority over the 50% data. 

It looks like the model is too big for your GPU :( Do you have access to a bigger GPU ? ( One free resource that you  could probably try is Kubernetes nautilus - https://ucsd-prp.gitlab.io/userdocs/tutorial/basic/ )

**Comment by Rafaelsoler13** [comment]
To see if I have understood it correctly, it would be to leave the rows of chr1, chr3 and chr6 (test non-peaks), but reduce to 80% and 50% the rest of the rows in the bed file that do not belong to those 3 chr (i.e. , reduce the validation and training group to 50% and 80%, right?). Wouldn't it be worth reducing the amount of chr used for training and validation? What is the theoretical concept behind subsampling this bed file?

I've had a look at the Nautilus tool, but despite being able to create an account, can I join a namespace if I don't belong to the organization that manages it?

Thank you very much for the help and recommendation!

**Comment by panushri25** [comment]
(1) Yes reduce training and validation to 50% and 80%. Don't leave out the test rows cause the pipeline will eventually use it for testing (You can also subsample the test rows to be honest, just the metrics won't be comparable across different subsampling runs).  

The concept behind subsampling the (train/valid) regions in the bed file - We are trying to address the problem that your bias model is still capturing CTCF and other TF motifs at even lower bias thresholds. By subsampling you are forcing the network to learn only the most frequent features (I.e Tn5) and leave out the tail end features (I.e CTCF and other TF motifs) on an average. 

This is quite rare occurrence that at 0.4 the bias model continues to learn TF motifs. How is the signal to noise in your peaks or the `FRIP` score? You can also train a bias model on another experiment (generated with similar protocol) and use it for transfer on this particular experiment. How did the bias model provided with the repository work with this particular experiment?

(2) I am not sure about this, I would email Nautilus support team -  they reply quite promptly.

**Comment by panushri25** [comment]
I will close this issue due to lack of activity. Please feel free to open it if there are anymore questions.

**Comment by Rafaelsoler13** [comment]
_How is the signal to noise in your peaks or the FRIP score?_
Where can I look for this score?

_How did the bias model provided with the repository work with this particular experiment?_
I could not run it because my GPU does not have enough memory

Is it possible to train the model using OpenCL or other AMD software instead of CUDA?

**Comment by panushri25** [comment]
(1) What peak caller are you using. I believe MACS2 provides this. 

(2) Sorry this is currently only implemented with CUDA. I dont think AMD or OpenCL will help if the GPU memory is not sufficient though.
