### ISSUE TITLE
Underscores in meta column when performing VEP

### ISSUE THREAD

**Issue by nikhilmilind** [kundajelab/chrombpnet#103]
The following line throws an error when I include any meta information with underscores when running the variant effect prediction using `snp_score`.

https://github.com/kundajelab/chrombpnet/blob/875affcde72c423025a6e1a19be63346a8fc0a74/chrombpnet/evaluation/variant_effect_prediction/snp_scoring.py#L140

Minimal Example of `SNP_DATA`:
```
chr1     100178435     A     G     chr1_100178435_A_G
```

Minimal Example command:
```
chrombpnet snp_score -snps snp_data.tsv -m model.h5 -g hg38.fa -op vep
```

**Comment by panushri25** [comment]
Is this the input you are providing `chr1     100178435     A     G     chr1_100178435_A_G`

**Comment by panushri25** [comment]
If so, refer to the documentation here about `SNP_DATA` https://github.com/kundajelab/chrombpnet/wiki/Variant-effect-prediction. Specifically the following line in the documentation - 

Meta-data column can be used to provide the following information such as p-value significance of the SNP, observed effect scores etc. This information will be added as column information to the output (see below) which you can use for downtream analysis. Provide any SNP related information to this column as **comma separated values.**

So comma separate them not underscores.  Hope that answers your question.

**Comment by nikhilmilind** [comment]
Yes, I am actually passing multiple values as comma separated, of which `chr1_100178435_A_G;rs551394` is one. For example, the full metadata column looks like this:

```
chr1     100178435     A     G     chr1_100178435_A_G;rs551394,0.7287298,0.171398798,True
```

**Comment by panushri25** [comment]
Ah okay the problem is that this field has underscores -  `chr1_100178435_A_G`. Can you use another way to join this string, replace underscores here with a "."  or a hyphen "-" maybe ? I am using underscore to join the cols and keep track of them through out the run. 

In the next version I will try to add a check for this and fix any formatting aprior.  Thanks for this issue.

**Comment by nikhilmilind** [comment]
Sounds good, thank you!

**Comment by panushri25** [comment]
Pointing main variant page to variant scorer tool -  https://github.com/kundajelab/variant-scorer
