### ISSUE TITLE
multi-task training

### ISSUE THREAD

**Issue by Y-ogativity** [kundajelab/chrombpnet#108]
Hi,

Thank you for sharing your excellent neural network model.
This post is not an issue but a question. Sorry for your inconvenience.

We utilized ChromBPNet in our lab with pseudobulk ATAC-seq reads generated from snATAC-seq and achieved promising outcomes. I am curious if ChromBPNet can handle multi-task training using multiple pseudobulk ATAC-seq reads generated from snATAC-seq, considering your development of multi-task models in bpnet.

**Comment by panushri25** [comment]
Hello Yohei Ogawa,

Thank you for your question.  Currently we do not have this feature inbuilt, but hope to release it in future versions.

Thank you,
Anu

**Comment by Y-ogativity** [comment]
Hi Anu,

Thank you for your reply and for developing such an amazing machine-learning architecture.

I understand. Because we are amazed by the ChromBPNet performance,  we want to ask about the cell type enriched regulatory grammar. I am looking forward to the feature!

Thanks,
Yohei

**Comment by panushri25** [comment]
Added this for future tools dev - https://github.com/kundajelab/chrombpnet/wiki/Software-dev
