### ISSUE TITLE
Chrombpnet getting killed on sherlock

### ISSUE THREAD

**Issue by dishasharma** [kundajelab/chrombpnet#109]
Hello

I tried running Chrombpnet on Sherlock Stanford servers, with resources assigned as below:

srun -p gpu -c 4 --gres gpu:1 --time 1-0 --pty bash

as mentioned in FAQ

Then I ran the below command:

“(chrombpnet) [dishas@sh02-12n04 /scratch/groups/tomq1/ChrombpnetTest/chrombpnet-master] (job 20243959) $ more script5.sh
#!/bin/bash
#SBATCH --job-name=Training
#SBATCH --mem=256G
ml system cairo/1.14.10
singularity  exec --nv -e --no-mount hostfs --bind /scratch/groups/tomq1/ChrombpnetTest/chrombpnet-master docker://kundajelab/chrombpnet:latest chrombpnet pipeline -ibam ch
rombpnet_tutorial/data/downloads/merged.bam -d “ATAC” -g chrombpnet_tutorial/data/downloads/hg38.fa -c chrombpnet_tutorial/data/downloads/hg38.chrom.sizes -p chrombpnet_tut
orial/data/peaks_no_blacklist.bed -n chrombpnet_tutorial/data/output_negatives.bed -fl chrombpnet_tutorial/data/splits/fold_0.json -b chrombpnet_tutorial/bias_model/ENCSR86
8FGK_bias_fold_0.h5 -o chrombpnet_tutorial/chrombpnet_model/
(chrombpnet) [dishas@sh02-12n04 /scratch/groups/tomq1/ChrombpnetTest/chrombpnet-master] (job 20243959) 

But I get error as below:

sha256:f97fba9b7b2019afeb2e1da35961216feb919b16320c2d01fbe4ebea31ae1698
INFO:    Creating SIF file...
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (495) bind mounts
Estimating enzyme shift in input file
Current estimated shift: +0/+0
Making BedGraph
Killed
Making Bigwig
needLargeMem: trying to allocate 0 bytes (limit: 100000000000)
[bwHdrRead] There was an error while reading in the header!
[pyBwOpen] bw is NULL!
Traceback (most recent call last):
  File “/opt/conda/bin/chrombpnet”, line 33, in <module>
    sys.exit(load_entry_point(‘chrombpnet’, ‘console_scripts’, ‘chrombpnet’)())
  File “/scratch/chrombpnet/chrombpnet/CHROMBPNET.py”, line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File “/scratch/chrombpnet/chrombpnet/pipelines.py”, line 31, in chrombpnet_train_pipeline
    build_pwm_from_bigwig.main(args)
  File “/scratch/chrombpnet/chrombpnet/helpers/preprocessing/analysis/build_pwm_from_bigwig.py”, line 46, in main
    bw = pyBigWig.open(args.bigwig)
RuntimeError: Received an error during file opening!

I ran separately read_bam_to_bigwig.py as well and bam_to_bigwig.sh as in old version of chrombpnet:

samtools view -b -@50 ../chrombpnet-master/chrombpnet_tutorial/data/downloads/merged.bam | bedtools bamtobed -i stdin | awk -v OFS="\t" '{if ($6=="-"){print $1,$2,$3-4,$4,$5,$6} else if ($6=="+") {print $1,$2+4,$3,$4,$5,$6}}' | bedtools genomecov -bg -5 -i stdin -g ../chrombpnet-master/chrombpnet_tutorial/data/downloads/hg38.chrom.sizes | bedtools sort -i stdin > merged_sorted.tmp2 

It shows Killed

Then I ran step by step pipes and I got to know it get killed at bedtools sort. Rest everything runs fine. Could you help me how to assign resources so it run smoothly? Or Is it something am i missing?

Thanks for the help.

**Comment by suragnair** [comment]
Linked to #106

**Comment by suragnair** [comment]
Yep that's the issue, you can replace it with `LC_COLLATE="C" sort -k1,1 -k2,2n` for now. Although I'm not sure why it's failing since you requested 256Gb and it shouldn't take more than that. How many reads do you have?

**Comment by dishasharma** [comment]
I am using the bam file from test data provided in the tutorial.

**Comment by dishasharma** [comment]
-rw-r--r-- 1 dishas tomq1 7.0G Mar 19  2021 rep1.bam
-rw-r--r-- 1 dishas tomq1 6.6G Mar 19  2021 rep2.bam
-rw-r--r-- 1 dishas tomq1 9.4G Mar 19  2021 rep3.bam
-rw-r--r-- 1 dishas tomq1  22G May 17 18:02 merged_unsorted.bam
-rw-r--r-- 1 dishas tomq1  22G May 17 19:12 merged.bam

**Comment by dishasharma** [comment]
rep1.bam	7.0G
rep2.bam	6.6G
rep3.bam	9.4G
merged_unsorted.bam	22G
merged.bam	22G

**Comment by akundaje** [comment]
We should really avoid merging BAMs (which requires sort and merge). Just
convert to tagAlign and merge. Much cheaper.

**Comment by dishasharma** [comment]
Ok Thank you! Trying that. :)

**Comment by panushri25** [comment]
I think this is related to Sherlock scheduler. 

there is apparently a 8gb memory / 1 core threshold setting on Sherlock. And the suggested solution was to let the scheduler allocate memory and only specify n cores. 

@dishasharma Can you try `-c 2` in your command

**Comment by dishasharma** [comment]
in this?

srun -p gpu -c 4 --gres gpu:1 --time 1-0 --pty bash

i should try:

srun -p gpu -c 2 --gres gpu:1 --time 1-0 --pty bash

right?

**Comment by panushri25** [comment]
Yes add in the memory flag, the memory limit you have now should not break though. Cause I tested this on most of the datasets on encode and it worked.

**Comment by dishasharma** [comment]
Its running good now. :) with more cpu and mem.
Thank you for the help!
