### ISSUE TITLE
check the existence of the fasta index before building a new one

### ISSUE THREAD

**Issue by DongzeHE** [kundajelab/chrombpnet#115]
Hello,

It seems like the when calling the `get_genomewide_gc` function, a fasta index file will be built regardless if there is an existing one. I would recommend checking this file before building or building it locally to the working dir as in my case, I don't have the write permission to the folder containing the fasta file. Thanks.

Best,
Dongze

**Comment by DongzeHE** [comment]
see #116

**Comment by panushri25** [comment]
Fixed in the dev version (on GitHub) for next release - https://github.com/kundajelab/chrombpnet/commit/4d95ad1ce6a7d896f550c647871023d27d2f1286
