### ISSUE TITLE
The input peak file 

### ISSUE THREAD

**Issue by DongzeHE** [kundajelab/chrombpnet#117]
Hello,

I am using chrombpnet for analyzing a 10x scATAC-seq dataset. As CellRanger exports a `peaks.bed` file containing the location of  all the peaks, I was trying to feed this file directly to `chrombpnet prep nonpeaks`. However, as there are only three columns in the `peaks.bed` file (the chromosome name, start position, and end position), chrombpnet threw me an error saying that the input peaks bed file misses the 10th column. The first lines in the `peaks.bed` looks like the following: 
```
chr1    5849030 5851628
chr1    8908553 8911071
chr1    9573523 9576054
```
If possible, could you please give me some advices on how to avoid this error? can I just add the column required by the function and assign all vlaues as `0`, or do I have to use some cell calling tool to generate the bed file that is expected by `chrombpnet prep nonpeaks`? Thanks in advance! Followings are the traceback from `chrombpnet`

```Traceback (most recent call last):
  File "/gstore/home/hed11/miniconda3/envs/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/gstore/home/hed11/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 115, in main
    get_gc_content.main(args_copy)
  File "/gstore/home/hed11/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/helpers/make_gc_matched_negatives/get_gc_content.py", line 31, in main
    summit=start+row[9]```

Best,
Dongze

**Comment by panushri25** [comment]
Hello @DongzeHE 

The formatting for the peaks bed file is documented here in the main page - https://github.com/kundajelab/chrombpnet. 

`Input peaks must be in narrowPeak file format, and must have 10 columns, with values minimally for chr, start, end and summit (10th column). Every region is centered at start + summit internally, across all regions. Example file with [ENCSR868FGK](https://www.encodeproject.org/experiments/ENCSR868FGK/) dataset - [peaks.bed](https://mitra.stanford.edu/kundaje/oak/akundaje/anusri/chrombpnet_data/input_files/ENCSR868FGK_relaxed_peaks_no_blacklist.bed)`

The remaining columns can have an empty character (e.g. `.`). How are you thresholding your peaks? Are they relaxed peaks set?  We recommend using macs2 with p-value parameter of 0.01 and also to call summits as documented here - https://github.com/kundajelab/chrombpnet/wiki/Preprocessing/.

**Comment by DongzeHE** [comment]
HI @panushri25,

Thanks so much for your reply. I am using ChromBPNet to analyze a single-cell ATAC-seq dataset from 10x Genomics. The files, including peaks and fragments, are generated by Cell Ranger. You can file the description of the output files from [here](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/overview)  and some example datasets from [here](https://www.10xgenomics.com/resources/datasets?query=&page=1&configure%5BhitsPerPage%5D=50&configure%5BmaxValuesPerFacet%5D=1000&refinementList%5Bproduct.name%5D%5B0%5D=Single%20Cell%20ATAC). The peaks are detected by Cell Ranger internally and you can find the alrogithms overview from [here](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/algorithms/overview). 

Currently what I am doing is to use the middle site of each peak, `(end-start)/2`, as the summit and set 4th-9th columns as `.`. If you don't think this is bad I will go with it cuz I have only limited time for this project. 

Furthermore, it will be really nice if ChromBPNet can have something like `--mode 10x` to take cellranger's output.

Thanks,
Dongze

**Comment by DongzeHE** [comment]
One more irrelevant but interesting question is that I saw that no matter how many GPUs were detected by tensorflow, only the first GPU was fully occupied. Is there a secret switch for turning on the multi-GPU mode?

Following was what was shown in ChromBPNet log:
```
tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 23678 MB memory:  -> device: 0, name: Q P, pci bus id: 0000:04:00.0, compute capability: 6.1
tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 23678 MB memory:  -> device: 1, name: Q P, pci bus id: 0000:07:00.0, compute capability: 6.1
tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 23678 MB memory:  -> device: 2, name: Q P, pci bus id: 0000:0b:00.0, compute capability: 6.1
```

Following is what I got from `nvidia-smi`
```nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        P        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Q P        On   | 00000000:04:00.0 Off |                  Off |
|124%   58C    P0   213W / 250W |  24189MiB / 24576MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Q P        On   | 00000000:07:00.0 Off |                  Off |
|126%   27C    P8    17W / 250W |    271MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Q P        On   | 00000000:0B:00.0 Off |                  Off |
|128%   28C    P8    18W / 250W |    271MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     20479      C   ...nvs/chrombpnet/bin/python    24187MiB |
|    1   N/A  N/A     20479      C   ...nvs/chrombpnet/bin/python      269MiB |
|    2   N/A  N/A     20479      C   ...nvs/chrombpnet/bin/python      269MiB |
+-----------------------------------------------------------------------------+```

**Comment by panushri25** [comment]
Hello @DongzeHE,

There is no multi-gpu mode at the moment, its not really required for training the models so its not enabled. You can use a different gpu by using  `CUDA_VISIBLE_DEVICES=3` before the command line tools to select a different gpu (3rd gpu).

For peak-calling I recommend you follow this section closely - https://github.com/kundajelab/chrombpnet/wiki/Preprocessing#peak-calling. And download the example files from the main page - https://github.com/kundajelab/chrombpnet for reference. With relaxed peak-calling you will expect about 100K+ peaks for reference. We will discuss and consider having the 10x mode for future versions, but it is not currently supported. 

Thank you,
Anu

**Comment by panushri25** [comment]
Also what you said makes sense -  middle site of each peak is (end-start)/2 is the summit and 4th-9th columns is .

**Comment by DongzeHE** [comment]
Wonderful. Thank you so much for clarifying all these. I appreciate it.
