### ISSUE TITLE
Is 10th column required for pred_bw?

### ISSUE THREAD

**Issue by yyoshiaki** [kundajelab/chrombpnet#118]
Hello,

Question related to #117.
`pred_bw` requires a 10-column bed as input for -r REGIONS, and needs the 10th column (summit). On the other hand, when making a signal prediction for an arbitrary region rather than the narrow peak bed region, I thought that the summit position is absent and meaningless.
For example, since there seems a limitation of length for the prediction, is it reasonable to use a tiled bed file, where the 10th column is a random value such as 500?
Also I thought it would be useful if -r could take bed3 as an input.

Best,
Yoshi

**Comment by panushri25** [comment]
Yes you can use the 10th column value as 500, and input overlapping windows (of about 250 bp) if you want to make predictions in other than peak regions.  The predictions are filled in by centering on the 10-th column and overlapping regions are resolved by the algorithm.

**Comment by panushri25** [comment]
Made a detailed note of this here - https://github.com/kundajelab/chrombpnet/wiki/FAQ. Hope this is helpful!  Thank you for your suggestion we will make it compatible in our future release.

**Comment by yyoshiaki** [comment]
Thank you very much for your quick help!
