### ISSUE TITLE
which file should I give to contribs_bw? chrombpnet.h5 or chrombpnet_nobias.h5?

### ISSUE THREAD

**Issue by DongzeHE** [kundajelab/chrombpnet#119]
Hello,

See the title. `chrombpnet pipeline` gave me three files in the `models` folder, not sure which one should be used in `chrombpnet contribs_bw`. 

Best,
Dongze

**Comment by DongzeHE** [comment]
One more question, is there a way to fine tune a bias model?

Say I have trained a bias model using the `nonpeaks_negatives.bed` file returned by running `chrombpnet prep nonpeaks` using the peaks obtained from all samples' fragments (both control samples and treatment samples). Do you think it is possible to make bias model also learn from the control samples' fragments on top of the nonpeaks (by fine tuning perhaps?), so that the final chrombpnet model can only detect the motifs that appears only in the treatment samples, but not in nonpeaks or control samples? 

If there is no such an fine-tuning option, can I merge the peaks called from control samples' fragments with the nonpeak regions and provide that merged.bed file as the `--nonpeaks` to run `chrombpnet pipeline bias`?

**Comment by panushri25** [comment]
Please use the `chrombpnet_nobias.h5` to get bias-corrected contribution tracks.

**Comment by panushri25** [comment]
The description of the output files is provided here - https://github.com/kundajelab/chrombpnet/wiki/Output-format. All the content can be found in the wiki - https://github.com/kundajelab/chrombpnet/wiki/

**Comment by panushri25** [comment]
We havent tried the setting you mentioned. I wouldn't recommend training your bias model on the control samples to regress out the control motifs though for the following reasons.  

(1) The default bias model being trained is a smaller capacity model with very small receptive field. This is meant for only capturing Tn5's effect. 
(2) The same TF can have varied effects on accessibility across both the controls and treatments. For these cases the TFs footprint might get distorted. I would train two different models on control and treatment and then do differential analysis on the contribution scores.

**Comment by DongzeHE** [comment]
Cool! Thanks for your suggestions!
