### ISSUE TITLE
sort: write failed: /tmp/sortID88dV: No space left on device

### ISSUE THREAD

**Issue by benliu5085** [kundajelab/chrombpnet#127]
Hey,

My name is Ben and I am trying to follow the tutorial and fail to use the chrombpnet pipeline with provided 3 samples (rep1~3).

Here are the error message:

> (chrombpnet) [bl2772@cerebrogpu03 chrombpnet]$ chrombpnet pipeline \
> >     -ibam chrombpnet_tutorial/merged.bam \
> >     -d    "ATAC" \
> >     -g    downloads/hg38.fa \
> >     -c    downloads/hg38.chrom.sizes \
> >     -p    chrombpnet_tutorial/peaks_no_blacklist.bed \
> >     -n    chrombpnet_tutorial/output_negatives.bed \
> >     -fl   chrombpnet_tutorial/splits/fold_0.json \
> >     -b    chrombpnet_tutorial/bias_model/ENCSR868FGK_bias_fold_0.h5 \
> >     -o    chrombpnet_tutorial/chrombpnet_model/
> Estimating enzyme shift in input file
> Current estimated shift: +0/+0
> Making BedGraph
> sort: write failed: /tmp/sortID88dV: No space left on device
> Traceback (most recent call last):
>   File "/n/core/Bioinformatics/research/bliu/Tools/miniconda/envs/chrombpnet/bin/chrombpnet", line 33, in <module>
>     sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
>   File "/n/core/Bioinformatics/research/bliu/chrombpnet/chrombpnet/CHROMBPNET.py", line 23, in main
>     pipelines.chrombpnet_train_pipeline(args)
>   File "/n/core/Bioinformatics/research/bliu/chrombpnet/chrombpnet/pipelines.py", line 21, in chrombpnet_train_pipeline
>     reads_to_bigwig.main(args)
>   File "/n/core/Bioinformatics/research/bliu/chrombpnet/chrombpnet/helpers/preprocessing/reads_to_bigwig.py", line 89, in main
>     generate_bigwig(args.input_bam_file,
>   File "/n/core/Bioinformatics/research/bliu/chrombpnet/chrombpnet/helpers/preprocessing/reads_to_bigwig.py", line 46, in generate_bigwig
>     auto_shift_detect.stream_filtered_tagaligns(p1, genome_fasta_file, p2)
>   File "/n/core/Bioinformatics/research/bliu/chrombpnet/chrombpnet/helpers/preprocessing/auto_shift_detect.py", line 56, in stream_filtered_tagaligns
>     out_stream.stdin.write(line)
> BrokenPipeError: [Errno 32] Broken pipe

I have requested 800GB memory for this job but it seems the pipeline still complains about no space left, can you help?

**Comment by panushri25** [comment]
I think its complaining about disk space, how much disk space do you have in the directory you intend to run this?

**Comment by benliu5085** [comment]
Hi, thanks for the quick reply. here is what I have, I should have plenty?

> [bl2772@cerebro bliu]$ df . -h
> Filesystem                          Size  Used Avail Use% Mounted on
> ionv3.sgc.loc:/ifs/SGC/Shared/Core  1.7P  1.5P  203T  88% /n/core

**Comment by benliu5085** [comment]
I think I have figured out this issue, I changed the ln 40

>    cmd = """awk -v OFS="\\t" '{{if ($6=="+"){{print $1,$2{0:+},$3,$4,$5,$6}} else if ($6=="-") {{print $1,$2,$3{1:+},$4,$5,$6}}}}' | sort -k1,1 | bedtools genomecov -bg -5 -i stdin -g {2} | bedtools sort -i stdin """.format(plus_shift_delta, minus_shift_delta, chrom_sizes_file)


to 

>     cmd = """awk -v OFS="\\t" '{{if ($6=="+"){{print $1,$2{0:+},$3,$4,$5,$6}} else if ($6=="-") {{print $1,$2,$3{1:+},$4,$5,$6}}}}' | sort -k1,1 -T . | bedtools genomecov -bg -5 -i stdin -g {2} | bedtools sort -i stdin """.format(plus_shift_delta, minus_shift_delta, chrom_sizes_file)


And this issue is resolved. 

I am going to close this, thank you!

**Comment by benliu5085** [comment]
sort -k1,1 -T .

**Comment by benliu5085** [comment]
in the helper/preprocess/reads_to_bigwig.py
