### ISSUE TITLE
Question about retrieving the peaks associated with the discovered motifs.

### ISSUE THREAD

**Issue by DongzeHE** [kundajelab/chrombpnet#129]
Hi,

I have successfully run ChromBPNet on my data and found interesting motifs in the final motif report. However, then we realize that it is not clear how we can retrieve the peaks that helped with finding each motif from this result https://github.com/kundajelab/chrombpnet/wiki/Denovo-motif-discovery . Traditional Motif discovery tools like HOMER will tell you the associated peaks for each discovered motifs. My question is: is there a way in ChromBPNet to do the similar thing as in HOMER?

Best,
Dongze

**Comment by panushri25** [comment]
@DongzeHE 

Denovo motif discovery here as documented is done using [tfmodisco-lite](https://github.com/jmschrei/tfmodisco-lite/). Yes the coordinates of the motifs extracted are stored in a tfmodisco object and the contents of the object are documented in the [tfmodisco-lite](https://github.com/jmschrei/tfmodisco-lite/) repo. Please refer to that.

Note that TFModisco is a global interpretation tool, intended to give you a summary of all the representative motifs found in the contribution scores. It is not intended to annotate every instance of the motifs occurrence. We will soon release a tool to do the later.

**Comment by DongzeHE** [comment]
Excellent. I will close the issue but It will be great if you can let me know when the tool is released! Thank you so much!

Best,
Dongze
