### ISSUE TITLE
Creating fragments.tsv per cell cluster from 10x ATAC data -> mix cells from distinct batches?

### ISSUE THREAD

**Issue by vitkl** [kundajelab/chrombpnet#130]
Hi

I am trying to workout the optimal way of applying chromBPNet to our cell atlas 10x datasets (multiome). When creating fragments.tsv per cell cluster from fragments.tsv of all batches (10x reactions) included in the study, is it appropriate to aggregate cells that have the same cell label but originate from distinct batches?

**Comment by akundaje** [comment]
Yes this should be fine.

**Comment by panushri25** [comment]
Closing this @vitkl Please feel free to open it if you have any more questions.
