### ISSUE TITLE
Question about biological understanding of the positive and negative contribution scores 

### ISSUE THREAD

**Issue by jasondanic** [kundajelab/chrombpnet#134]
Hello,

Thank you for developing the excellent tool ChromBPNet.

I am interested in gaining a biological understanding of the positive and negative contribution scores in practice.

Here's the situation:
We observe enriched motifs in regions with continuous positive contribution scores, but at the same time, there are TF motifs enriched in the negative part. I can comprehend that a negative prediction might imply certain TFs playing a repressive role (as discussed here: https://github.com/kundajelab/chrombpnet/issues/100#issuecomment-1515699262).

However, while using chromVAR to calculate the TF motif deviation score for predicting TF activity enrichment, we notice that some TF motifs enriched in regions with negative contribution scores also exhibit high deviation scores within the same cluster. Does this not seem paradoxical from a biological perspective?

I would like to initiate a discussion on how to interpret this phenomenon biologically.

Thank you.

**Comment by akundaje** [comment]
What are the specific motifs. Can you share a screenshot of the MODISCO
results.

**Comment by jasondanic** [comment]
> results.
Thanks for prompt reply.

Screenshot presenting as follow:
![image](https://github.com/kundajelab/chrombpnet/assets/45625464/c02d821b-e42c-421f-b3d8-08c68f041616)

STAT3 looks like a proper example.

**Comment by akundaje** [comment]
Yes STAT3 I would say is a real negative motif.

Notice the very low seqlet count for the others. They are typically
happening in specific rare sequence contexts where there is motif
competition (e.g. multiple instances of BCL11A) and one instance may be
downweighted. It is unclear to us as yet whether these are real or just
model artifacts. There is prior evidence that as motif homotypic density
increases, activity initially increases, then saturates and then often
drops indicating that at high density some fraction of motifs effectively
have a negative impact. For now I would ignore these low seqlet count
patterns.

-Anshul.

**Comment by jasondanic** [comment]
I believe your explanation has clarified large part of my question. I will try to further understand relevant background knowledge, and I will close this question after this reply.

Thanks again.

**Comment by Brawni** [comment]
Hello, 

Following this thread i wonder what a negative profile score means biologically? Further i see instances where motifs have negative contributions profiles and positive count profiles. How would you biologically interpret this combination? Im attaching an example here:

<img width="1132" height="89" alt="Image" src="https://github.com/user-attachments/assets/c4c6d40e-c9b8-41a4-b5c9-2d678bae5074" />

Thanks so much !!
