### ISSUE TITLE
Larger sample than population issue

### ISSUE THREAD

**Issue by sid5427** [kundajelab/chrombpnet#138]
Hi Anushri,

Sorry - I don't think I haver permission to reopen a closed issue - any case this issue is independent of the previous thread

This is to follow up on error message I get on some of our chrombpnet runs- ValueError: Cannot take a larger sample than population when 'replace=False'

Refer to my reply in this previous thread - https://github.com/kundajelab/chrombpnet/issues/132#issuecomment-1696323465

**Comment by panushri25** [comment]
replied on the thread, I get notifications for the closed issues too so following up there
