### ISSUE TITLE
Detecting/quantifying motif interaction effects?

### ISSUE THREAD

**Issue by snaqvi1990** [kundajelab/chrombpnet#140]
Hi again!

Is there a preferred way to look for interactions between motifs in ChromBPNet models? I ask because I have fine-tuned a ChromBPNet model pre-trained on ATAC for a slightly different task (predicting sensitivity to TF dosage) and am seeing some results that may suggest interactions between motifs. Specifically, in the attached modisco results, pos_patterns.pattern_2 and neg_patterns.pattern_0 are nearly identical, suggesting that the same motif can contribute positively or negatively to TF dosage sensitivity depending on the context. I know that in the original BPNet paper a synthetic approach was used, i.e. injecting motifs into random DNA sequences -- is that still the way you guys would recommend to assess if there are interactions?

Thanks,
Sahin

![Image 9-8-23 at 1 59 PM](https://github.com/kundajelab/chrombpnet/assets/7546459/2267bd52-c92f-4c12-8b1a-fe73d49d67e8)

**Comment by panushri25** [comment]
Yes I would still inject motifs into random DNA sequences, will get back here if I have any updates and tools regarding this.
