### ISSUE TITLE
Question on step2_make_bigwigs_from_bams.sh and predict_to_bigwig.py

### ISSUE THREAD

**Issue by zixiaowang17** [kundajelab/chrombpnet#142]
Hi,

Thanks for building this amazing package!

I noticed there is a step2_make_bigwigs_from_bams.sh in workflow/tutorial/ directory, but this was not found in "wiki" tutorials, is it because the steps in step2_make_bigwigs_from_bams.sh was already embedded in on of the steps of train function? I was wondering whether I should follow the code in or the codes in workflow/tutorial/. It seems there are more differences between the workflow (full_workflow.sh) and wiki.

Also, I failed to run the file predict_to_bigwig.py, this function seems to be unbuilt in the main function modules, I was wondering if you have any suggestions and comments on this.

Really appreciate your time.

Thanks,
Zixiao

**Comment by panushri25** [comment]
Yes please follow the wiki, the workflow/tutorial/  will be deprecated. https://github.com/kundajelab/chrombpnet/wiki

Follow this command line for generating prediction bigwigs - 
https://github.com/kundajelab/chrombpnet/wiki/Generate-prediction-bigwigs
