### ISSUE TITLE
Questions about the number of seqlets observed from modisco command

### ISSUE THREAD

**Issue by KyleFerchen** [kundajelab/chrombpnet#145]
I've extracted the seqlet positions from the .h5 file outputs of calling modisco on the tn5 counts head contribution score file. I set the -n (MAX_SEQLETS) options to 1e6 as recommended in the documentation. However, I noticed that some chromosomes don't have any seqlets called on them. I am getting roughly 1e5 seqlets called total.

Is there something limiting the number of seqlets being called that can be adjusted with the modisco command?

Separately, I wrote a script to scan through the bigwig contribution score file, and could point to many more regions that have high absolute average contribution scores across (about 35 times more seqlets total are called), and these span all of the chromosomes. So it seems the modisco command is limiting in the number of seqlets it is identifying. Is there something that can be adjusted to increase the number of seqlets recovered? Or would you simply recommend using the identified seqlets to scan for other regions that may have high contributions for regions that were not captured by the modisco algorithm?

Could you also explain what steps modisco-lite are using to call the seqlets? It is not clear from the github what peak calling algorithm is identifying the summits.

**Comment by snaqvi1990** [comment]
Hi Kyle, would you be able to share your script to find high contribution regions? I am trying to do something similar and also noticed that modisco only stores a representative subset of seqlet instances

**Comment by panushri25** [comment]
Hello @KyleFerchen  and @snaqvi1990 

Yes modisco does not annotate all the regions of the genome. Its a global interpretation tool (not a local one) meant for summarizing the set of representative motifs in your contribution scores. So it utilizes a set of seqlets that are enough to achieve this. 

I would recommend opening a issue here ( https://github.com/jmschrei/tfmodisco-lite) to get a detailed explanation for all the steps in modisco-lite.  

Regarding finding a way to comprehensively and reliably annotate all the seqlets - we are working on a tool to achieve this and will keep you posted. 

Thank you,
Anu

**Comment by KyleFerchen** [comment]
Thank you @panushri25, I'll look at the tfmodisco-lite code in more detail.

Hi @snaqvi1990, to find the high scoring contribution regions, I applied a brute force method of scanning through windows of a fixed size (Eg. <window_size> = 20 bp) and taking all windows that have an average absolute contribution score above a given threshold (Eg. <cs_thresh> = 0.005). 

I'm simply using pyBigWig to read in the contribution score bigwig values at the loci/peaks of interest. The peaks are annotated in a table with chr, start, and end coordinates, as well as a candidate target gene. Then I'm using the pandas "rolling" function to calculate the average contribution score at each window. This is calculated simultaneously for a set of contribution score bigwig sample files saved in a specific directory.  Overlapping windows are removed by ranking each of the windows found above the given threshold, and removing those that overlap with a prior, higher ranking window. So the resulting dataframe (<region_anno>) has the coordinates of the window, the original peak from which that window came, its offset within that peak, the max_cs observed among all tested sample bigwigs, and the min_cs observed among all tested sample bigwigs. The code I have below was written specifically for the samples I had, but it could be quickly rewritten to apply to a different dataset:

https://github.com/KyleFerchen/snippets/blob/main/example_call_seqlet_windows.ipynb

(For 1kb peaks, 20 bp windows, and 32 sample bigwig files, the scoring takes about 40 seconds / 1,000 peaks tested on my computer. So it's not too bad, but definitely could be optimized. This was just my first pass at trying a solution)

```
# Read in the peak locations for processing
peak_anno = pd.read_csv(path_peak_nominations)
peak_anno["chr"] = [i.split(":")[0] for i in peak_anno.iloc[:,2].values]
peak_anno["start"] = [int(i.split(":")[-1].split("-")[0]) for i in peak_anno.iloc[:,2].values]
peak_anno["end"] = [int(i.split("-")[-1]) for i in peak_anno.iloc[:,2].values]
peak_anno
```
![image](https://github.com/kundajelab/chrombpnet/assets/15041556/d6eee630-c196-4fac-85b0-966b035272cd)

```
# Get bigwig files and make names for those bigwig files
path_to_bigwigs = "output/chrombpnet/browser_visualization/"\
    "count_scores_bw_extended_peak_set/fold_0/"

list_bw_files = os.listdir(path_to_bigwigs)

list_sample_names = [i.replace(".bw","") for i in list_bw_files]
```

```
# Read in bigwig files
bw_dict = {}
for tmp_name, tmp_file in zip(list_sample_names, list_bw_files):
    bw_dict[tmp_name] = pyBigWig.open(os.path.join(path_to_bigwigs, tmp_file))
```
```
# Define a window size (constant size for seqlets)
window_size = 20
# Threshold for average contribution score over the window
cs_thresh = 0.005

region_anno = []
for i in range(peak_anno.head(1000).shape[0]):
    print(f"{i+1}/{peak_anno.shape[0]} peaks processed...", 
        end="\r", flush=True)
    # Store tmp values for current peak
    tmp_chr, tmp_start, tmp_end, tmp_gene = peak_anno[["chr", "start", "end", "gene"]].iloc[i,:4].values
    tmp_peak_size = tmp_end - tmp_start

    # Extract bigwig values
    test = pd.DataFrame(\
        [bw_dict[i].values(tmp_chr, tmp_start, tmp_end) for i in list_sample_names],
        index=list_sample_names)

    # Get window means
    test = test.rolling(\
        window=window_size, 
        min_periods=window_size, 
        axis=1).mean().iloc[:,window_size-1:]
    test.columns = list(range(tmp_peak_size-window_size+1))

    # Identify non-overlapping highest scoring regions
    list_i = test.abs().max(axis=0).sort_values(ascending=False)
    list_i = list_i[list_i > cs_thresh].index.values
    saved_i = []
    while(len(list_i) > 0):
        i_sel = list_i[0]
        saved_i.append(i_sel)
        tmp_check = list_i - i_sel
        list_i = list_i[(tmp_check < (-1*window_size)) | (tmp_check > window_size)]

    # Save footprints for the current peak
    region_anno.append(pd.DataFrame({\
            "chr": tmp_chr,
            "start": tmp_start + np.array(saved_i),
            "end": tmp_start + np.array(saved_i) + window_size - 1,
            "gene": tmp_gene,
            "peak": f"{tmp_chr}:{tmp_start}-{tmp_end}",
            "offset": saved_i,
            "max_cs": test.loc[:,saved_i].max(axis=0).values,
            "max_cs_group": test.loc[:,saved_i].idxmax(axis=0).values,
            "min_cs": test.loc[:,saved_i].min(axis=0).values,
            "min_cs_group": test.loc[:,saved_i].idxmin(axis=0).values},
        index=saved_i))

region_anno = pd.concat(region_anno)
```

```
# Close the bigwig files
bw_dict = {}
for tmp_name in bw_dict:
    bw_dict[tmp_name].close()
```

```
region_anno
```
![image](https://github.com/kundajelab/chrombpnet/assets/15041556/1e4c8e6a-763f-4e0d-acef-f57a36843cbb)

```
# Save all regions
path_output = "output/chrombpnet/seqlets/expanded_peak_set_fold_0/"
region_anno.to_csv(os.path.join(path_output, "seqlet_regions_absolute_cs_above_0_005.csv"),
    header=True, index=False)
```

Let me know if this is helpful!
Best,
Kyle

**Comment by snaqvi1990** [comment]
Thanks so much Kyle, this is super helpful!
