### ISSUE TITLE
Custom motifs

### ISSUE THREAD

**Issue by erikla** [kundajelab/chrombpnet#148]
Hi,

Is it possible to edit or replace the default motif list with a custom one?
Can one simply edit the motifs.meme.txt and expect TFmodisco output reports to work properly?
Thanks for producing so many nice features of chrombpnet software.

Best,
E

**Comment by panushri25** [comment]
Yess! just make sure the formatting is in the meme format.  And directly use the `modisco motifs` command from https://github.com/jmschrei/tfmodisco-lite/tree/main

Thank you,
Anu

**Comment by panushri25** [comment]
Thank you for the encouraging words!

**Comment by panushri25** [comment]
Hope this answers your question.  Happy to answer any more questions you may have, please reply back here. I will close this as addressed for now.
