### ISSUE TITLE
filtering peaks and non-peak regions by proximity to TSS

### ISSUE THREAD

**Issue by dustin-cram** [kundajelab/chrombpnet#151]
In your [preprint](https://www.biorxiv.org/content/10.1101/2022.12.20.520743v1), the inputs to both the bias and TF models exclude genomic regions within 750 bp of TSSs.  However, I don't see anything in this repo that suggests that this filtering is part of the ChromBPNet pipeline.

I'm wondering if this is something that I should be doing manually, or was that specific to the experiment described in the preprint because it was concerned only with enhancer signatures as opposed to promoters?

**Comment by panushri25** [comment]
Hello,

The url you linked is not our pre-print. This is one of the application papers of our work. Out pre-print is not out yet and will be out in a month. 

Yes this particular paper is only concerned with enhancer signatures and hence they excluded peak regions close to TSSs. 

Thank you,
Anu
