### ISSUE TITLE
TypeError: get_regions() missing 1 required positional argument: 'regions_used'

### ISSUE THREAD

**Issue by MZZheng** [kundajelab/chrombpnet#154]
Hello

I used "chrombpnet bias pipeline" train my model, and then use 
" chrombpnet contribs_bw -m ./results/models/bias.h5 -r hudep2_1.narrowPeak -g hg19.fa -c hg19.chrom.sizes -op hudep2_scores_"
to get the contribution scores. But I get an error:
Saving 'profile' scores
Traceback (most recent call last):
  File "/home/mzheng09/.conda/envs/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/home/mzheng09/.conda/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 68, in main
    importance_hdf5_to_bigwig.main(args_copy)
  File "/home/mzheng09/.conda/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/importance_hdf5_to_bigwig.py", line 30, in main
    regions = bigwig_helper.get_regions(args.regions, SEQLEN)
TypeError: get_regions() missing 1 required positional argument: 'regions_used'

Can you help me figure out how to fix the error? Thank you very much.

**Comment by panushri25** [comment]
Hello, which version of chrombpnet are you running

**Comment by MZZheng** [comment]
I installed the chrombpnet a week ago, using the method as below:
##Create a clean conda environment with python >=3.8
conda create -n chrombpnet python=3.8
conda activate chrombpnet
##Install non-Python requirements via conda
conda install -y -c conda-forge -c bioconda samtools bedtools ucsc-bedgraphtobigwig pybigwig meme

**Comment by panushri25** [comment]
oh okay, can you update it? I made a new release that should fix this

**Comment by panushri25** [comment]
just do `pip install chrombpnet --upgrade` in the environment i.e do` conda activate chrombpnet` first.

**Comment by MZZheng** [comment]
OK, thank you so much!

**Comment by panushri25** [comment]
Also I recommend you add yourselves to the watchers list on the github page. You will get notified of any changes made to the repo.

**Comment by panushri25** [comment]
Please update to the latest 0.1.6 version and regenerate your contribution scores. It should fix this error.

**Comment by panushri25** [comment]
Let me know if you see any more issues.
