### ISSUE TITLE
Training ChromBPNet from a checkpoint/previous-saved model

### ISSUE THREAD

**Issue by arodel21** [kundajelab/chrombpnet#156]
Hello again!

Is there a way of training ChromBPNet from a previous saved model or a checkpoint?

Thanks in advance.

**Comment by panushri25** [comment]
I am not saving all checkpoints to be mindful of disk space. But here is how I think you can do this -

Create a fork of the current repo and set the following argument - `save_best_only` -  to False in this line here - https://github.com/kundajelab/chrombpnet/blob/8e7fd8ae71eaadae6594a98c18ee7c93ebd6eb2e/chrombpnet/training/train.py#L32

You can find more information about this argument here - https://keras.io/api/callbacks/model_checkpoint/

**Comment by arodel21** [comment]
And what is the name of the file the checkpoint is saved with? Is it chrombpnet.h5 or chrombpnet_no_bias.h5?

Thank you!

**Comment by panushri25** [comment]
You will have to look at the format but it will be chrombpnet _epoch(etc id).h5 You will need to isolate the chrombpnet_no_bias.h5 for each of the checkpoints yourself, I can point you to the function to do this. 

May I ask why you will need this, perhaps I can be of better of help?

**Comment by arodel21** [comment]
I could not find the file h5 you mention. I just need the checkpoints because of the limitations the cluster I am using to train the model gives me.

**Comment by VErconi** [comment]
Hi panushri25!

I'm here several months later with the same limitations raised by arodel21.
I have gpu usage limited to 12h and checkpoint would be my only hope to arrive at the end of the training with in house data.

Once` save_best_only` is changed, how can I specify to the chrombpnet pipeline where to take the .h5 model checkpoint from which to start back?

I couldn't retrieve any parameter through which I could specify this (https://github.com/kundajelab/chrombpnet/wiki/ChromBPNet-training) 

Thank you for your support with this!
