### ISSUE TITLE
Using chrombpnet for STARR-Seq data 

### ISSUE THREAD

**Issue by otastet** [kundajelab/chrombpnet#158]
Hi, 
First of all thank you very much for this valuable tool. We have used it already for ATAC-Seq data alongside the variant effect prediction. 
I wanted to know your thoughts on using it with [STARR-Seq](https://www.sciencedirect.com/science/article/pii/S0888754315300100), a functional assay that quantifies enhancer strengths. We are particularly interested in estimating the effect of variants on the enhancer signals. 

Thank you very much.

**Comment by panushri25** [comment]
Hello @otastet, Our lab is working on related architecture specific to STARR-seq but it is currently under development and will be released soon. So please check back later. Thank you!
