### ISSUE TITLE
Training chromBPNet takes too much time

### ISSUE THREAD

**Issue by lzj1769** [kundajelab/chrombpnet#161]
Hi,

I am currently training a chromBPNet for an ATAC-seq sample with ~200K peaks. However, it takes ~12 hours for one epoch. 
See below screenshot
<img width="2157" alt="Screenshot 2023-12-08 at 20 38 24" src="https://github.com/kundajelab/chrombpnet/assets/9947922/5af62369-fac3-4959-a1a8-d9f16dc07223">

So I want to ask how to make the training process faster.

Any ideas are appreciated.

Thanks,
Zhijian

**Comment by akundaje** [comment]
Are you using a GPU? What type of GPU?

It should not take so long if you are using a decent GPU eg V100 or A100

Anshul

**Comment by lzj1769** [comment]
Hi Anshul,

I think I found the problem.
For some weird reason, TensorFlow doesn't use GPU properly. After fixing this issue, everything looks great!

Thanks,
Zhijian

**Comment by hermandebeukelaer** [comment]
Hi @lzj1769, I am running into a similar performance problem. Training the model from the tutorial is very slow, no output yet after more than 1 hour execution time. How did you discover TensorFlow wasn't using the GPU properly and how did you fix it?

**Comment by lzj1769** [comment]
Hi @hermandebeukelaer 

You can check if tf is using GPU using the command: nvidia-smi

To fix it, be sure you installed the correct version of CUDA, Tensorflow, and cuDNN.
