### ISSUE TITLE
Generating contribution score bigwig file

### ISSUE THREAD

**Issue by PetHabib** [kundajelab/chrombpnet#162]
Hi, 

when I tried to generate the contribution score, chromebpnet was able to generate all files (*.counts_scores.h5, *.interpret.args.json, *.interpreted_regions.bed, *.profile_scores.h5) except .bw one and it did not generate any error, do you have any idea why this happened?

Thank you in advance.

**Comment by sid5427** [comment]
Hi Peter,

I think we need to update our chrombpnet installation to version 0.1.5 - which is the latest version. I also got the same error and then I noticed in the change log - https://github.com/kundajelab/chrombpnet/compare/v0.1.4...v0.1.5

@panushri25 - is updating to the newest version the correct solution for the error below?

Error using v0.1.4 while running the contribution score step- 
`2023-12-08 01:15:08.482486: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet_oct_2023/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/users/sen2qb/conda_env/chrombpnet_oct_2023/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 68, in main
    importance_hdf5_to_bigwig.main(args_copy)
  File "/users/sen2qb/conda_env/chrombpnet_oct_2023/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/importance_hdf5_to_bigwig.py", line 30, in main
    regions = bigwig_helper.get_regions(args.regions, SEQLEN)
TypeError: get_regions() missing 1 required positional argument: 'regions_used'`

**Comment by PetHabib** [comment]
Hey Sid,

Thank you very much for letting me know! I will update and see if it solves this.

**Comment by panushri25** [comment]
Thanks @PetHabib for your answer.

Yes thats correct, please upgrade to the latest version for fixing this. 

I am going to release another version in a bit, will keep you posted here. So you can upgrade to that.

**Comment by panushri25** [comment]
Please update to the latest 0.1.6 version and regenerate your contribution scores. It should fix this error, 0.1.5 has an incorrect and incomplete fix.

**Comment by sid5427** [comment]
Great - thanks for the quick resolution!
