### ISSUE TITLE
Predicting bias

### ISSUE THREAD

**Issue by arodel21** [kundajelab/chrombpnet#167]
Hello again!

I have a silly question:

When predicting using only the bias_model_scaled.h5, do I get the bias itself or do I get the data without corrected bias?

Thank you!

**Comment by panushri25** [comment]
Only the bias. However, in ATAC-seq, the bias is so pronounced in the observed reads that the predicted bias might closely resemble the uncorrected data.

**Comment by arodel21** [comment]
So then ChromBPNet substracts the bias from the data?

**Comment by arodel21** [comment]
@panushri25, I am also a bit confused with the output of the **chrombpnet pred_bw** function. There is an output file called output_prefix_bias_preds.bed and it is described in the tutorial as "Bed file containing filtered regions for which predictions were generated using bias.h5". If I understood correctly, this file contains the regions where bias was found, so then these regions are filtered out of the data?

Thanks again
