### ISSUE TITLE
footprint bw track

### ISSUE THREAD

**Issue by YichaoOU** [kundajelab/chrombpnet#168]
Hello,

There are 3 bw files from `pred_bw`. 

```
bias.bw
chrombpnet.bw
chrombpnet_nobias.bw
```

I suppose `chrombpnet.bw` is for footprint track?

Thanks,
Yichao

**Comment by panushri25** [comment]
If you want a track to compare with the observed tracks directly you will use - `chrombpnet.bw` (which is not corrected for bias)

But if you want something which is corrected for bias and reflects the footprints of TFs - please use `chrombpnet_nobias.bw
`

Hope this answers your question, otherwise please post back. 

I will improve the documentation to clarify this, thank you!

**Comment by YichaoOU** [comment]
Thanks! Below is a screenshot for 3 bw tracks for one sample (same sample).

`chrombpnet_nobias.bw`

`chrombpnet.bw`

`bias.bw`

It seems the `chrombpnet.bw` is in high resolution, which looks more like a footprint track? I want to find some differential footprints comparing different conditions.

![image](https://github.com/kundajelab/chrombpnet/assets/19987406/95735c69-f4aa-41b3-9fd0-b4ddcf05482b)

**Comment by panushri25** [comment]
What do you mean by high resolution?

**Comment by panushri25** [comment]
Can you lay it over with the observed bw

**Comment by YichaoOU** [comment]
`High resolution`. For example, the last track is a footprint track using HINT-ATAC (different cell, as compared with the above chrombp tracks). You can see for HINT-ATAC footprint track is more similar (in terms of the style) to `chrombpnet.bw` than `chrombpnet_nobias.bw`. 

I will add observed bw later. Thanks for the quick reply!

![image](https://github.com/kundajelab/chrombpnet/assets/19987406/a5338a4f-eda1-48f8-8d08-f68d53f23934)

**Comment by panushri25** [comment]
If you add the observed track you will be able to tell the difference yourself i think. I suggest getting contribution score bigwigs for some of these regions to get some sense, you will see that `chrombpnet_nobias.bw` will directly overlay with motifs and show footprints. 

Are you referring to the spikiness as high resolution? I am a little confused can you elaborate?
