### ISSUE TITLE
TFmodisco lite doesn't seem to run

### ISSUE THREAD

**Issue by rb56** [kundajelab/chrombpnet#175]
Hello,

I'm trying to run TFmodisco-lite on counts_scores.h5 file to carry out motif discovery. However, the command doesn't seem to run and no output or error is generated. The job ends due to Timeout of GPU resources. 

This is the code I use to run TF modisco in the chrombpnet virtual environment
`modisco motifs -i new.CS.counts_scores.h5 -n 1000000 -o $wordir_path/$pred_prefix_modisco_results.h5
`
Is anyone facing the same error?

**Comment by panushri25** [comment]
For modisco lite related help you can post here - https://github.com/jmschrei/tfmodisco-lite/

Modisco lite does not use GPU btw, If you can post the log or out that would be helpful for debugging
