### ISSUE TITLE
Difference between counts and profile

### ISSUE THREAD

**Issue by arodel21** [kundajelab/chrombpnet#178]
Hello!

When generating the bigwig prediction, what is the difference between the counts motif discovery and the profile motif discovery? I know that one is for the counts and the other for the shape, but I don't fully understand this description.

Thanks in advance.

**Comment by panushri25** [comment]
Ah, so ChromBPNet models have two outputs one is for total signal  (total counts in region which is scalar) and another is for total shape (the probability vector of the profile in a region itself). So the contribution scores correspondt o each of these heads. 

Intuitively, the contributions you find from the profile head usually are are based on the influence they have on shaping the profile (e.g deeper footprints) on the other hand  contributions you find from the counts head are based on the influence they have on total accessibility (for example, a TF may never footprint or have high contact with the DNA, but might be crucial for accessibility at the region). 

Let me know if this helps, I will clarify this in the wiki as well!

**Comment by arodel21** [comment]
Thank you @panushri25 !
