### ISSUE TITLE
Choice of NEG_TO_POS_RATIO_TRAIN in preparing background region

### ISSUE THREAD

**Issue by saninta0212** [kundajelab/chrombpnet#179]
Hello!

I was wondering if I could get some clarification on how the NEG_TO_POS_RATIO_TRAIN default has been selected. According to the tutorial the default has been set 2, but could I get the reasoning behind why this 2 was chosen and how can I decide if I should choose a different cut-off?

The second question I wanted some clarification on is in this code file here: https://github.com/kundajelab/chrombpnet/blob/master/chrombpnet/helpers/make_gc_matched_negatives/get_gc_matched_negatives.py, the default for "--neg_to_pos_ratio_train" ratio default has been set to 1. Is there a disparity with the tutorial and why was 1 selected here? 

If I could also get some explanation on how selecting different values here might affect my downstream analysis that would be great!

Thank you.

**Comment by panushri25** [comment]
NEG_TO_POS_RATIO_TRAIN setting to 2 makes sure you have enough negative regions to train your bias model. If you are using a pre-trained bias model from the repo (and not training a bias model from scratch) a 1:1 ratio also works fine.
