### ISSUE TITLE
Nit: Small inconsistency on "Generate contribution score bigwigs" wiki page for names of output files

### ISSUE THREAD

**Issue by ryanhzhao** [kundajelab/chrombpnet#181]
On the wiki page for generating contributions cores, the outputs for count scores are listed as `output_prefix.count_scores.h5`
[https://github.com/kundajelab/chrombpnet/wiki/Generate-contribution-score-bigwigs](https://github.com/kundajelab/chrombpnet/wiki/Generate-contribution-score-bigwigs)

However, in the code they are generated as `args_copy.output_prefix + ".counts_scores.h5"` (count**s** instead of count)
[https://github.com/kundajelab/chrombpnet/blob/master/chrombpnet/CHROMBPNET.py#L65](https://github.com/kundajelab/chrombpnet/blob/master/chrombpnet/CHROMBPNET.py#L65)

**Comment by panushri25** [comment]
Ah thanks for catching the typo!
