### ISSUE TITLE
Obtaining BAM file with removed TN5-bias

### ISSUE THREAD

**Issue by arodel21** [kundajelab/chrombpnet#182]
Hello again,

Thank you all for your help in my previous issues.

I was wondering if you could guide me on producing a BAM file with removed Tn5-bias. This would require only running the bias removal model and not the chrombpnet model itself (?)

Thank you!
Best wishes.

**Comment by panushri25** [comment]
You cannot obtain BAM files with removed Tn5 bias (I dont think it is possible to correct  for Tn5 at the reads in  BAM file directly, because of the sparsity in reads), you can only get prediction bigwigs. 

Hope this clarifies please post back if you have more questions.

**Comment by arodel21** [comment]
Thank you @panushri25 !
