### ISSUE TITLE
chrombpnet_deepshap command not found

### ISSUE THREAD

**Issue by saninta0212** [kundajelab/chrombpnet#183]
I am trying to generate deepSHAP values and run TF-modisco on the deepSHAP contribution scores. However, running script from here (https://github.com/kundajelab/chrombpnet/tree/master/chrombpnet/evaluation/interpret) is giving me an error:  chrombpnet_deepshap: command not found. I could run modisco report and the other commands but not the chrombpnet_deepshap. Some help on this would be appreciated!

**Comment by panushri25** [comment]
Sorry that README is outdated. I will remove it, please follow the tutorial links here -  https://github.com/kundajelab/chrombpnet/wiki
