### ISSUE TITLE
Using uncorrected chrombpnet model for generation of prediction bigwigs

### ISSUE THREAD

**Issue by Gechyb** [kundajelab/chrombpnet#184]
I initially trained my bias model with bias_threshold_factor of 0.5 and got a pearsonr value of -0.42. Then I went ahead and retrained the bias model with threshold of 0.6 and this increased the pearsonr value to -0.18. However when I trained the chrombpnet model, the model according to the average of the max of profies is uncorrected. The max of the tn5 profiles is 0.0035. Since I do not have a pre-trained bias model to retrain my chrombpnet model, is it okay to move ahead with generating prediction bigwigs with the uncorrected chrompbnet model? Or should I retrain my bias training using a bias_threshold_factor of 0.7?

**Comment by panushri25** [comment]
Did you try using the pre-trained bias model given with the repo?

**Comment by panushri25** [comment]
I can discuss more options depending on where you are stuck currently let me know!

**Comment by panushri25** [comment]
Closing this thread due to inactivity, please reopen if you are seeing more issues.
