### ISSUE TITLE
Rev comp to augment sequences

### ISSUE THREAD

**Issue by saninta0212** [kundajelab/chrombpnet#187]
I am a little confused on how exactly is reverse complemented sequence with their accessibility profile is applied as part of the data augmentation process. From my understanding of the code, randomly some sequences are cropped and revcomped but a description of what exactly is done for data augmentation would be great

**Comment by panushri25** [comment]
We have the detailed description in our pre-print which will be released very soon, stay tuned. 

In the meantime, here is the script which includes all the augment operations - https://github.com/kundajelab/chrombpnet/blob/master/chrombpnet/training/utils/augment.py
