### ISSUE TITLE
problem in 'motif hit calling'

### ISSUE THREAD

**Issue by GGboy-Zzz** [kundajelab/chrombpnet#193]
Hi,
Sorry to pose issue here for 'finemo_gpu' error, but I need to get some support qucikly.
my code as above, 
1. ` finemo extract-regions-chrombpnet-h5 -c ${sample}.profile_scores.h5 -o `$outdir/${sample}` 
2. `finemo` call-hits \-M pp -r ${sample}.npz \-m ${sample}_modisco.h5 \-p ${sample}_peaks_no_blacklist.bed \ -d cuda \-o $outdir/${sample} `

the generate error is：
`in call_hits raise ValueError(f"Input sequences of shape {sequences.shape} and/or "  ValueError: Input sequences of shape (368638, 4, 1000) and/or input contributions of shape (368638, 4, 1000) are not compatible with region count of 368651`
I checked the 'finemo/main.py', and I found there is a different number of pekas in my regions file and peaks file, but I'm sure that when when generated contribution score h5, I used the same narrow peaks file as here. I didnt know what happened, and hope your suggestions, thanks!

**Comment by austintwang** [comment]
Hello! I've replied to your original post here:
https://github.com/austintwang/finemo_gpu/issues/21#issuecomment-2177361546
