### ISSUE TITLE
installation error on Mac M1

### ISSUE THREAD

**Issue by ratheraarif** [kundajelab/chrombpnet#195]
Hi,

thank you for making this wonderful tool.

I tried to install the package however I am repeatedly getting the following error

<img width="1018" alt="image" src="https://github.com/kundajelab/chrombpnet/assets/46924431/df67ed3c-2ca9-4efd-a700-313177210ba2">

I also tried to install tensorflow 2.8, but it still results in the same error.

**Comment by panushri25** [comment]
It seems that there is some conflicting version of tensorflow package on your system. I recommend opening a conda environment or using the docker setup.

**Comment by ratheraarif** [comment]
I am actually working in condo environment., but it does not let me move forward
