### ISSUE TITLE
Cannot access example files - 403 Forbidden

### ISSUE THREAD

**Issue by terencewtli** [kundajelab/chrombpnet#199]
None of the tutorial files are available - eg [nonpeaks](https://mitra.stanford.edu/kundaje/oak/anusri/chrombpnet_data/input_files/ENCSR868FGK_relaxed_peaks_no_blacklist.bed)

**Comment by akundaje** [comment]
Anusri - can we move all links pointing to mitra on the Github to Zenodo
links instead since mitra links are not stable or permanent.

**Comment by TFHan** [comment]
Hey same issue here, are there any updates on this? thanks for your effort!

**Comment by panushri25** [comment]
Hello, all the links have been uploaded here on zenodo - https://zenodo.org/records/7443683, I will replace the specific links in the main page, in the meantime feel free to use this! Thank you!

**Comment by panushri25** [comment]
All the links are updated to cloud/zenodo links now.

please reopen this if there are any more issues.
