### ISSUE TITLE
 Seeking Advice on Comparing ChromBPNet Predictions Across Models

### ISSUE THREAD

**Issue by XuanrZhang** [kundajelab/chrombpnet#203]
Dear Developer @panushri25,

I am seeking your advice on comparing ChromBPNet predictions across different models. I have trained several ChromBPNet models for different cell types. When comparing predictions and contribution scores across these models, I’ve noticed that the data scales are different. Would you recommend normalizing the model predictions and contribution scores before making comparisons across different models?

Additionally, before model training, did you normalize the input BAM file?

Thanks for your attention.

Best,
Xuan

**Comment by panushri25** [comment]
Hello @XuanrZhang 

We did not normalize the BAM file. You could consider normalizing the predictions by read depth (total number of reads).  Profile contributions scores wont require normalization but counts contribution scores need to be normalized as well. You can consider normalizing using percentiles for this.

Thank you,
Anu
