### ISSUE TITLE
Does ChromBPNet normalize the input data at any point?

### ISSUE THREAD

**Issue by idf-io** [kundajelab/chrombpnet#204]
Dear ChromBPNet team,

I'm using ChromBPNet for my project and it's essential for me to know if `ChromBPNet` normalizes the ATAC-seq data as part of the workflow.

Currently I am using your `reads_to_bigwig.py` tool from the `preprocessing` section to create the bigwigs from my ATAC-seq fragment reads.

I couldn't find any normalization procedure within the pre-processing code. Does `ChromBPNet` normalize during training?

I would be very thankful for your help.

Thank you in advance and best regards,
Ian

**Comment by akundaje** [comment]
No it is trained on raw counts and predicts expected counts per base. You
can normalize as you wish post hoc

**Comment by idf-io** [comment]
Thank you!

**Comment by idf-io** [comment]
Thank you!
