### ISSUE TITLE
chrombpnet for Mac M2 

### ISSUE THREAD

**Issue by wgao688** [kundajelab/chrombpnet#206]
Hi there, thanks for this great package! I am wondering if you have gotten it to successfully download on Mac M2? It seems like the Nvidia container toolkit is not supported?

**Comment by panushri25** [comment]
Sorry I havent tried specifically installing on Mac, you might find more help on torch/tensorflow support channels on how to install these packages on Mac. As long as the packages are installed chrombpnet package should install without any issues.
