### ISSUE TITLE
Continuing pipeline from set point

### ISSUE THREAD

**Issue by BartTheeuwes** [kundajelab/chrombpnet#207]
Dear,

Thank you all for making this package. I'm currently trying to run ChromBPNet on the tutorial data. I have noticed that every time I rerun chrombpnet pipeline, I need to restart from scratch and delete the old chrombpnet_model folder. Because of this, it is regenerating the bigwig files from the Bam input every time. I expect that it should just be able to continue from a previously generated bigwig file, especially when training the same model with different folds... Is there a way to make the chrombpnet pipeline pick up from a specific point, or even just specifically from the training step?

All the best,
Bart

**Comment by akundaje** [comment]
We will try to add this feature in the future (early next year) with a
significant refactor as well. We currently don't have bandwidth to add this
feature.
