### ISSUE TITLE
Scipy nanmean issue in predict.py for chrombpnet docker

### ISSUE THREAD

**Issue by pl92297** [kundajelab/chrombpnet#208]
Hello, 

Running chrombpnet through the kundajelab docker image currently fails at the prediction step fails with the following error:

`ImportError: cannot import name 'nanmean' from 'scipy' (/opt/conda/lib/python3.9/site-packages/scipy/__init__.py)`

This may have been a versioning issue, but nanmean was deprecated for scipy in 0.18.0 and will not work for the installed version of scipy in the docker container (scipy 1.13.1). Either changing the docker scipy version or modifying predict.py to use `numpy` nanmean and nanstd may fix this.

Thanks!

**Comment by panushri25** [comment]
duplicate report #201
