### ISSUE TITLE
chrombpnet prep nonpeaks does not complete

### ISSUE THREAD

**Issue by Brawni** [kundajelab/chrombpnet#210]
Dear devs, 

I'm stuck at trying to generate non-peak regions using function `chrombpnet prep nonpeaks` as the progress bar freezes at 22% with my current peakset. I tested this on tutorial and the function successfully complete and also on a subset of the peaksets i input sampling 200,000 peaks out of the ~800,000 peaks i'm using. I tried to run it with more memory / cores but it doest change and it always stops at 22%. 

Any input would be much appreciated!

Thank you!!

**Comment by akundaje** [comment]
800,000 is way too many peaks. Restrict to the top 250K peaks

**Comment by Brawni** [comment]
Will do thanks!
