### ISSUE TITLE
how to pass mean contribution scores to TFmodisco

### ISSUE THREAD

**Issue by Brawni** [kundajelab/chrombpnet#212]
Dear devs, 

I am training chrombpnet model for multiple training/validation sets as suggested and then generate contribution scores for each of the folds. I then want to run TFmodisco-lite but probably not necessary to run it for each fold? So what would be the easiest way for me to average h5 contribution scores before passing it to `modisco motifs` function? 
Thanks so much!

P.s. this tool is a game changer for scATAC-seq analysis and for this i'm extremely grateful to all of you!

**Comment by panushri25** [comment]
Thank you for your kind words!

yes, average h5 contribution scores before passing it to modisco motifs function. We will introduce a function to do this soon, but you can simply loop through the h5 files, load them and average them based on the keys and create an equivalent h5 output for modisco.
