### ISSUE TITLE
how to extract contribution scores using genomic positions 

### ISSUE THREAD

**Issue by Brawni** [kundajelab/chrombpnet#213]
Hello there,

What would be the best strategy to extract contribution scores associated with genomic positions of a given TF that doesnt show up in TFmodisco reports? I was thinking to use genomic positions computed by chromVAR to do that but not sure how to query the output files. Also, is it this even a good idea?

Thank you

**Comment by panushri25** [comment]
Do you want to query the TF motifs in your contribution score bigiwgs?

**Comment by Brawni** [comment]
yes, but I'm not sure it makes sense. My issue is that i'm looking for a TF which i expect to be present (according to RNA expression and chromvar deviations) in the data but i dont see it in the TFmodisco results. Ultimately I would like to compare the average contribution scores between two cell types for this TF (although not sure contr. scores can be directly compared across models?) and also study its co-occurrence with other TFs of interest (also not present in TFmodisco results) in peaks. Any thoughts on this? Thanks so much!!

**Comment by panushri25** [comment]
If the TF that your looking for is not present in your TF Modisco results, it is possible that the TF is not a direct contributor to the accessibility in that celltype (meaning it might be binding in peaks after the regions are already made accessible by other pioneer TFs, so this TF is not responsible for accessibility but it can continue to contribute to downstream effects like expression). What celltype and what TF are you looking for?

profile contribution scores can be compared across models as they are already self-normalized 

Refer to the resource pointed here to study co-occurence https://github.com/kundajelab/chrombpnet/wiki/Motif-hit-calls

**Comment by Brawni** [comment]
I see...so chromBPnet best model pioneer TFs? Wouldn't opportunistic TFs also contribute to accessibility? So if TFmodisco doesnt report the TFs you would not recommend doing a more supervised analysis?  
Im looking at SOX9 and SOX6 in two tumor cells pseudo-bulks, each including around 1k cells. I would like to compare these TF between these two subsets in terms of genome-wide overall score, co-occurrence and differences in specific loci perhaps.   
Thanks for your response and for the resource link!

**Comment by akundaje** [comment]
Not all TFs contribute directly to accessibility even though many bind accessible DNA. E.g. Nanog in ESCs, TAL1 in erythroid cells. There are experiments knocking out these TFs that show no changes at all in accessibility. So if u are interested in TFs that affect downstream processes such as activation or transcription, no sequence model of accessibility will pick these up directly. You would have to use other approaches that directly supervise on TF ChIP-seq data or downstream activity measures (e.g. histone marks, gene expression) or u explicitly use motifs of the TF of interest to estimate heuristic enrichments (like ChromVAR does).

-Anshul

**Comment by Brawni** [comment]
Interesting...I didn't know that. Thanks for the explanations Anusri and Anshul!
