### ISSUE TITLE
pybigwig (0.3.18) is incompatible with Python 3.7.9

### ISSUE THREAD

**Issue by SuhasSrinivasan** [kundajelab/chrombpnet#42]
The Conda installation instructions begin with creating an environment with Python 3.7.9.

One of the required (requirements.txt) conda packages is pybigwig 0.3.18.

However, this is not compatible with Python 3.7.9.

Below is the reported error.

```
conda install -c bioconda pyBigWig==0.3.18
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pybigwig==0.3.18 -> python[version='>=3.10,<3.11.0a0']

Your python: python=3.7.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - pybigwig==0.3.18 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.7.9 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

**Comment by annashcherbina** [comment]
Thanks for the heads up, you can use pybigwig 0.3.17 with python 3.7.9 -- we are releasing an updated version shortly with this corrected.

**Comment by SuhasSrinivasan** [comment]
Thank you for the super quick response!

**Comment by SuhasSrinivasan** [comment]
Also, needed numpy version is 1.21.5 for pybigwig 0.3.17
Requirements lists as numpy==1.19.5

**Comment by SuhasSrinivasan** [comment]
Also suggest that the Requirements are installed first with `pip` and then switch over to bioconda packages.

```
git clone https://github.com/kundajelab/chrombpnet.git
cd chrombpnet
pip install -r requirements.txt
conda install -y -c bioconda samtools bedtools ucsc-bedgraphtobigwig 
```

**Comment by panushri25** [comment]
Hey Suhas,

How is the order of pip and condo important? The README suggests first doing conda and then pip correct? Why does doing pip first and then condo matter?

Thank you,
Anu

**Comment by SuhasSrinivasan** [comment]
> Hey Suhas,
> 
> How is the order of pip and condo important? The README suggests first doing conda and then pip correct? Why does doing pip first and then condo matter?
> 
> Thank you, Anu

It is a suggestion just to organize sequence of package installation steps.
First fetch pip packages (most general repo) then fetch conda package from bioconda (specific repo).

**Comment by panushri25** [comment]
I see, do you have any insights on how (and if it) makes a difference in  the environment setup?

**Comment by SuhasSrinivasan** [comment]
It is a suggestion for logical consistency, it would not affect package installation.

However, the requirements can actually be split up into two, one for conda packages and other for pip-only packages.

As this method is recommended by Anaconda, to first use conda (since it has resolver, etc.) and then pip. Please see below link.
https://www.anaconda.com/blog/using-pip-in-a-conda-environment#:~:text=In%20summary%2C%20when%20combining%20conda,to%20install%20any%20remaining%20software.

**Comment by SuhasSrinivasan** [comment]
> I see, do you have any insights on how (and if it) makes a difference in the environment setup?

Also, Issue #46 was due to a user assuming `requirements.txt` can be parsed with conda too. 
So if pip appears first, more attention is paid to it and then conda/bioconda command can be included.
