### ISSUE TITLE
Suggestion for Data Downloads

### ISSUE THREAD

**Issue by SuhasSrinivasan** [kundajelab/chrombpnet#43]
This is a suggestion to improve the data download process for the tutorial.

As the data is downloaded from ENCODE (AWS S3), it is somewhat slow at 40 to 45MB/s and happens in a sequential manner.  

Given that each file is several GBs and the download is slow, it would be better to group all downloads together and parallelize this.

First, provide a `data/downloads` folder through GitHub with a `downloadfiles.txt`. This will help skip the directory creation step.

```
----
downloadfiles.txt
----
# download bams
https://www.encodeproject.org/files/ENCFF077FBI/@@download/ENCFF077FBI.bam -O rep1.bam
https://www.encodeproject.org/files/ENCFF128WZG/@@download/ENCFF128WZG.bam -O rep2.bam
https://www.encodeproject.org/files/ENCFF534DCE/@@download/ENCFF534DCE.bam -O rep3.bam

# download overlap peaks (default peaks on ENCODE)
https://www.encodeproject.org/files/ENCFF333TAT/@@download/ENCFF333TAT.bed.gz -O overlap.bed.gz

# download reference data
https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz hg38.fa.gz

# download reference chromsome sizes
https://www.encodeproject.org/files/GRCh38_EBV.chrom.sizes/@@download/GRCh38_EBV.chrom.sizes.tsv -O hg38.chrom.sizes

# download blacklist regions 
https://www.encodeproject.org/files/ENCFF356LFX/@@download/ENCFF356LFX.bed.gz -O blacklist.bed.gz
```

`cd data/downloads`
`cat downloadfiles.txt | xargs -n 1 -P 2 wget -q`

Rely on xargs return code for final download status.  

**Not tested.**

**Comment by panushri25** [comment]
Ah I see, thank you for the suggestion I will test it out.
