### ISSUE TITLE
Unable to install tfmodisco

### ISSUE THREAD

**Issue by sroyyors** [kundajelab/chrombpnet#46]
hi,
I am installing the packages within a condo environment. I am using conda install "package". This worked for almost everything but tfmodisco. I tried both

 conda install modisco==0.5.16.0

and 

pip install git+git:https://github.com/kundajelab/tfmodisco.git

The first gave "PackagesNotFoundError"
The second just errored out, maybe I have the wrong url?

**Comment by SuhasSrinivasan** [comment]
Hi,

I am not a maintainer but a recent user.
The workaround for this is `pip install` 
Please use `pip` for all the packages listed in `requirements.txt`.
Use `conda` only for the bioconda packages i.e., samtools, bedtools and ucsc-bedgraphtobigwig.

I have suggested a better way to structure the package installation https://github.com/kundajelab/chrombpnet/issues/42#issuecomment-1139109600

Running into issues with ucsc-bedgraphtobigwig: https://github.com/kundajelab/chrombpnet/issues/45

**Comment by sroyyors** [comment]
thanks, that worked. I was avoiding pip install so that it would not install things directly under .local/lib and instead put it under the conda specific environment.  So far it seems to be ok.
