### ISSUE TITLE
TensorFlow 2.4 incompatibility with CUDA 11.1+

### ISSUE THREAD

**Issue by SuhasSrinivasan** [kundajelab/chrombpnet#49]
When starting using TensorFlow 2.4 there is a dependency on `libcusolver.so.10` which is not present in CUDA 11.1+.
```
“Could not load dynamic library ‘libcusolver.so.10’; 
dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory”
```

CUDA 11.1+ ships with `libcusolver.so.11`.

**Workaround 1**:
Update to TensorFlow 2.5.3.

**Workaround 2**:
Create a symbolic link
```
$ locate libcusolver.so.11
$ sudo ln -s /<path_to_cuda_lib>/libcusolver.so.11 /<path_to_cuda_lib>/libcusolver.so.10
```

**Comment by annashcherbina** [comment]
Please use this branch for now: 

https://github.com/kundajelab/chrombpnet/blob/create-pip-module/requirements.txt#L9
