### ISSUE TITLE
bedGraphToBigWig outdated

### ISSUE THREAD

**Issue by zji90** [kundajelab/chrombpnet#69]
When I run bedGraphToBigWig there is an error:

bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

This is due to an outdated bedGraphToBigWig being used. Is it possible to update bedGraphToBigWig to the newest version?

**Comment by annashcherbina** [comment]
Hi @zji90 thanks for posting. 

So the 2 places in the requirements where this touches on are : 
* pyBigWig, which is already pinned at the latest released version(https://github.com/deeptools/pyBigWig/tags) 
* In Readme, there is instruction to install bedGraphToBigwig: 
```
conda install -y -c bioconda samtools bedtools ucsc-bedgraphtobigwig
```
This should actually give you the latest bedGraphToBigWig version (https://anaconda.org/bioconda/ucsc-bedgraphtobigwig) 

It sounds like you might have an outdated bedGraphToBigwig on your system? Running the conda install as above (after uninstalling your current version) should hopefully resolve the problem. Let us know if it doesn't.
