### ISSUE TITLE
error with example data

### ISSUE THREAD

**Issue by zji90** [kundajelab/chrombpnet#70]
Hi,

I am trying to run through the example pipeline. I have updated bedGraphToBigWig but encountered the following error. The error happens for both bedGraphToBigWig version v2.9 and v4, which I believed are the latest version. I wonder how this can be fixed.

non zero bigwig entries in the given chromosome:  5802613
"chrombpnet_pwm_from_bigwig -i $bigwig_prefix"_unstranded.bw" -g $reference_fasta -o $bigwig_prefix"_bias_pwm" -c "chr20" -cz $chrom_sizes" command failed with exit code 0.

By the way, I manually downloaded and rerouted bedGraphToBigWig. Using conda to install bedGraphToBigWig still gives me the old version that is not compatible with libssl: libssl.so.1.1

**Comment by annashcherbina** [comment]
Hi @zji90 -- exit code 0 actually means the command succeeded, apologies for the confusing message. We will update it in the code. If a png file containing a pwm was generated, it means things are working.
