### ISSUE TITLE
alternative input

### ISSUE THREAD

**Issue by zji90** [kundajelab/chrombpnet#73]
Hi,

I wonder if input formats other than bam can be accepted. bam files are pretty large and it would be great if I can use bed or fragment files instead.

**Comment by panushri25** [comment]
Hello sorry I missed this and yes we can provide scripts which uses fragment files. Will work on merging that.

Thank you for the suggestion!

**Comment by suragnair** [comment]
@zji90 please see #75 in the meanwhile
