### ISSUE TITLE
error on step 5 for single cell dataset

### ISSUE THREAD

**Issue by sid5427** [kundajelab/chrombpnet#81]
Good day,

I am trying to run chrombpnet on a scATACseq mouse dataset, separated by cell cluster. I also checked if the bias pwm image generated by step matches the sample on the instructions - which it does.
Then trained the bias model on the most abundant cell type as suggested and was then running step 5 after subsampling had finished.
Unfortunately this step did not complete and returned an error. The error states - 

```
[Parallel(n_jobs=10)]: Done  23 out of  23 | elapsed:    0.0s finished
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet/bin/chrombpnet_modisco", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet_modisco')())
  File "/users/sen2qb/testing_area/chrombpnet/chrombpnet/evaluation/modisco/run_modisco.py", line 108, in main
    tfmodisco_results = modisco.tfmodisco_workflow.workflow.TfModiscoWorkflow(
  File "/users/sen2qb/conda_env/chrombpnet/lib/python3.8/site-packages/modisco/tfmodisco_workflow/workflow.py", line 391, in __call__
    seqlets_to_patterns_result = seqlets_to_patterns(
  File "/users/sen2qb/conda_env/chrombpnet/lib/python3.8/site-packages/modisco/tfmodisco_workflow/seqlets_to_patterns.py", line 1184, in __call__
    pattern.compute_subclusters_and_embedding(
  File "/users/sen2qb/conda_env/chrombpnet/lib/python3.8/site-packages/modisco/core.py", line 777, in compute_subclusters_and_embedding
    twod_embedding = sklearn.manifold.TSNE(
  File "/users/sen2qb/conda_env/chrombpnet/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py", line 1122, in fit_transform
    self._check_params_vs_input(X)
  File "/users/sen2qb/conda_env/chrombpnet/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py", line 793, in _check_params_vs_input
    raise ValueError("perplexity must be less than n_samples")
ValueError: perplexity must be less than n_samples
```
attached log files - [standard err log file](https://1drv.ms/u/s!Alr23pNlJf37jbcC6uPNIyR95MiRNw?e=RCQjjh)
[standard out log file ](https://1drv.ms/u/s!Alr23pNlJf37jbcDIUGP_Qcuc75AUQ?e=z1mg42)

my sklearn version = 
sklearn.__version__
'1.1.3'

Would appreciate any help resolving this issue.

Thanks.
- Sid

**Comment by panushri25** [comment]
Hello @sid5427 

Try reducing the version of  scikit-learn to 1.1.0 or lower  and try again? We will soon release an updated version with a fix to this. 

Thank you and let me know how this works!

**Comment by panushri25** [comment]
@sid5427 Before downgrading the version of scikit - can you try using modisco lite - https://github.com/jmschrei/tfmodisco-lite and letting us know if that fixes the issue?

**Comment by sid5427** [comment]
Hi Panushri,

Sure I can try using modisco lite - I looked at the commands - `modisco motifs -s ohe.npz -a shap.npz -n 2000 -o modisco_results.h5` and I am not sure what ohe.npz, shap.npz files are - are they created somewhere as part of step 5? 

This was my original step 5 command - 
`step5_interpret_bias_model.sh <path>/genome.fa data/subsample_peaks/30K.subsample.overlap.bed models/bias_model/bias.h5 models/bias_model/interpret/`

appreciate the help.

**Comment by panushri25** [comment]
You should have a file `models/bias_model/interpret/ bias.profile.h5` and `models/bias_model/interpret/bias.counts.h5`

so you can run the following  - 

`modisco motifs -i models/bias_model/interpret/bias.counts.h5 -n 50000 -w 500  -o modisco_counts_results.h5`

`modisco motifs -i models/bias_model/interpret/bias.profile.h5  -n 50000  -w 500 -o modisco_profile_results.h5`

**Comment by sid5427** [comment]
Hi Panushri,

I am creating a second conda environment with a clean install of chrombpnet and then tfmodisco-lite - 
however I am having some issues cloning chrombpnet - I tried `git clone https://github.com/kundajelab/chrombpnet.git` and then entered my username and password on prompting - that did not work. I also directly downloaded the zip version, unzipped it and tried to install via ` pip install -e chrombpnet` - that returned an error saying - `ERROR: file:///users/sen2qb/testing_area/second/chrombpnet-master/chrombpnet`

I can see setup.py for sure and this had installed about a month back - not sure what I am doing wrong. Any help would be appreciated.

**Comment by sid5427** [comment]
> Hi Panushri,
> 
> I am creating a second conda environment with a clean install of chrombpnet and then tfmodisco-lite - however I am having some issues cloning chrombpnet - I tried `git clone https://github.com/kundajelab/chrombpnet.git` and then entered my username and password on prompting - that did not work. I also directly downloaded the zip version, unzipped it and tried to install via ` pip install -e chrombpnet` - that returned an error saying - `ERROR: file:///users/sen2qb/testing_area/second/chrombpnet-master/chrombpnet`
> 
> I can see setup.py for sure and this had installed about a month back - not sure what I am doing wrong. Any help would be appreciated.

fixed this - needed to use `pip install -e .`

**Comment by sid5427** [comment]
> You should have a file `models/bias_model/interpret/ bias.profile.h5` and `models/bias_model/interpret/bias.counts.h5`
> 
> so you can run the following -
> 
> `modisco motifs -i models/bias_model/interpret/bias.counts.h5 -n 50000 -w 500 -o modisco_counts_results.h5`
> 
> `modisco motifs -i models/bias_model/interpret/bias.profile.h5 -n 50000 -w 500 -o modisco_profile_results.h5`

and please correct me if I am wrong - step 5 (and step 7) technically is not needed for running step 6. It's to do a sanity check and see if correct motifs...

**Comment by panushri25** [comment]
Step 6 is training - Step 5 and Step 7 for quality checking

**Comment by sid5427** [comment]
Hi Panushri,

I used modisco lite to interpret the bias model - it did output the modisco_profile_results.h5 but not modisco_counts_results.h5

I backtracked to check and the bias.counts_scores.h5 file is really small 
bias.counts_scores.h5 - 3kb
bias.profile_scores.h5 - 655,571kb
- I am attaching the logs of this step here - [standard err](https://1drv.ms/u/s!Alr23pNlJf37jbcjItnsLsWVuplCzQ?e=ZVM6Ff)
[standard out](https://1drv.ms/u/s!Alr23pNlJf37jbckyIl45cZ140IbeQ?e=kHYZrP)

We are also facing some issues with step 6 - it looks like training the chrombpnet model for smaller single cell clusters return an error.
Here is a step 6 log for one of the smaller clusters for which the training did not work - any way to resolve this issue?
[step 6 err](https://1drv.ms/u/s!Alr23pNlJf37jbcaO6LQLN36PJ7pVA?e=IMChxv)
[step 6 out](https://1drv.ms/u/s!Alr23pNlJf37jbcbEYEHoDLA8txeDg?e=a8VUNi)

Appreciate the help.

**Comment by panushri25** [comment]
(1) for some reason your counts interpretations did not run to completion. And your error is not saying anything about it. Can you rerun and tell me if it throws any error?

(2) Regarding step 6 error - How many reads are in these clusters? I have included this check for extremely low-read depth datasets (generally < 5M reads gives this error).

**Comment by sid5427** [comment]
Hi Panushri - for issue 1 - same thing again, it did not complete and no error.
For issue 2 - these are from really small clusters - about 30-40 cells. Estimated under 1million reads.

I have switched to using the new release version of chrombpnet - are there any major difference between the older one and the v0.1.0 release version?

**Comment by sid5427** [comment]
Hello,

So after using the new version of chromBPnet - I first tried the bias training step. Unfortunately I get this error while running in - 

```
/tmp/tmpfpfc0tgb is not case-sensitive sorted at line 81973505.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.
[urlOpen] Couldn't open /scratch/sen2qb/output/TEA_HSC_atac_bias/auxiliary/data_unstranded.bw for reading
[urlOpen] Couldn't open /scratch/sen2qb/output/TEA_HSC_atac_bias/auxiliary/data_unstranded.bw for reading
[pyBwOpen] bw is NULL!
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet_new/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/users/sen2qb/conda_env/repos/chrombpnet/chrombpnet/CHROMBPNET.py", line 38, in main
    pipelines.train_bias_pipeline(args)
  File "/users/sen2qb/conda_env/repos/chrombpnet/chrombpnet/pipelines.py", line 283, in train_bias_pipeline
    build_pwm_from_bigwig.main(args)
  File "/users/sen2qb/conda_env/repos/chrombpnet/chrombpnet/helpers/preprocessing/analysis/build_pwm_from_bigwig.py", line 46, in main
    bw = pyBigWig.open(args.bigwig) 
RuntimeError: Received an error during file opening!
```

I am not sure what's going on - my command looks like this - 
```
chrombpnet bias pipeline \
-ibam bams/TEA_HSC_atac_possorted_bam.bam \
-d "ATAC" \
-g /data/salomonis2/LabFiles/Daud/Genomes/multi_ome/hg38/fasta/genome.fa \
-c /data/salomonis2/LabFiles/Daud/Genomes/multi_ome/hg38/fasta/sizes_hg38_genome.txt \
-p narrowpeaks/TEA_HSC_atac_possorted_bam_peaks.narrowPeak \
-n nonpeaks/TEA_HSC_atac/TEA_HSC_atac_negatives.bed \
-fl splits/fold_0.json \
-b 0.5 \
-o /scratch/sen2qb/output/TEA_HSC_atac_bias/

```

The narrowpeak file comes from macs2 peak calling and the negatives bed file comes from the previous step3_get_background_regions.sh script.

I also get a similar error if I try using a previously generated bias.h5 for the chrombpnet model training - 

```
/tmp/tmpj5a1lvif is not case-sensitive sorted at line 81973505.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.
[urlOpen] Couldn't open /scratch/sen2qb/output/TEA_HSC_atac_MAIN/auxiliary/data_unstranded.bw for reading
[urlOpen] Couldn't open /scratch/sen2qb/output/TEA_HSC_atac_MAIN/auxiliary/data_unstranded.bw for reading
[pyBwOpen] bw is NULL!
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet_new/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/users/sen2qb/conda_env/repos/chrombpnet/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/users/sen2qb/conda_env/repos/chrombpnet/chrombpnet/pipelines.py", line 31, in chrombpnet_train_pipeline
    build_pwm_from_bigwig.main(args)
  File "/users/sen2qb/conda_env/repos/chrombpnet/chrombpnet/helpers/preprocessing/analysis/build_pwm_from_bigwig.py", line 46, in main
    bw = pyBigWig.open(args.bigwig) 
RuntimeError: Received an error during file opening!

```

command used for above - 
```
chrombpnet pipeline \
-ibam bams/TEA_HSC_atac_possorted_bam.bam \
-d "ATAC" \
-g /data/salomonis2/LabFiles/Daud/Genomes/multi_ome/hg38/fasta/genome.fa \
-c /data/salomonis2/LabFiles/Daud/Genomes/multi_ome/hg38/fasta/sizes_hg38_genome.txt \
-p narrowpeaks/TEA_HSC_atac_possorted_bam_peaks.narrowPeak \
-n data/negatives_data_TEA_HSC_atac_possorted_bam_peaks/negatives_with_summit.bed \
-fl splits/fold_0.json \
-b models/bias_model_TEA_HSC_atac_possorted_bam/bias.h5 \
-o /scratch/sen2qb/output/TEA_HSC_atac_MAIN/

```

any help would be appreciated!

**Comment by panushri25** [comment]
Yes looking into it

**Comment by panushri25** [comment]
The error is occurring at your bam to bigwig conversion.  Can you share your bam file to reproduce the error. 

Also I will release a version where you will be able to train for even 1 million read clusters.

**Comment by panushri25** [comment]
I have a test version that should fix both the issues. Can you test it out and let me know -

You can install it as follows

`python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ chrombpnet==0.2.13`

If this doesnt work you can share the bam files that can reproduce this error maybe.

**Comment by panushri25** [comment]
Just referencing the pull request for this #83

**Comment by sid5427** [comment]
Hi Anushri,

Unfortunately, the test version did not work for our psuedobulk scRNA bam files. It did work for another set of bulk atac bam files. I have sent you an email with a link to download one of our bam files. Please look for a **onedrive shared link** in your work email. Would appreciate it if you can take a look into it.

We are also facing another issue - we get this error while running `chrombpnet modisco_motifs` on candidate regions - it does not generate the html or pdf reports. I ran this after the chrombpnet model was generated for the above bulk datasets

```
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet_new2/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/users/sen2qb/conda_env/chrombpnet_new2/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 93, in main
    modisco_command = "modisco report -i {} -o {} -m {}".format(args.output_prefix+"_modisco.h5",args.output_prefix+"_reports",meme_dir)
NameError: name 'meme_dir' is not defined
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet_new2/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/users/sen2qb/conda_env/chrombpnet_new2/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 93, in main
    modisco_command = "modisco report -i {} -o {} -m {}".format(args.output_prefix+"_modisco.h5",args.output_prefix+"_reports",meme_dir)
NameError: name 'meme_dir' is not defined
```

TF-modisco seems to work fine when generating the sanity check files from the 30k subsamples as part of the `chrombpnet pipeline` & `chrombpnet bias pipeline` commands.

We have another question regarding the output - is there any output file which contains say footprint coordinates + motif coordinates?

Appreciate the help and clarifications!

**Comment by panushri25** [comment]
Hey @sid5427 

(1) Will look at the bams you sent over today.

(2) Just fixed a typo that should fix the modisco_motifs command error - this test version should have it - 

`python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ chrombpnet==0.2.14`

I am going to see if anything needs to be changed inorder to make things work for your bam files and then merge these changes in the main repo. Will keep you posted.

(3) oh yeah! So we have test version of those scripts - using modisco motifs to annotate the motif coordinates. We have found that the motif coordinates are super set of footprint coordinates. Let me circle back with Anshul on releasing this, I might make it available through a beta testing version of the repo if that interests you.

**Comment by panushri25** [comment]
Alsp @sid5427 what is the error with the bams you sent over? Same as before?

**Comment by sid5427** [comment]
Hi Anusri - yes the error mentioned here - https://github.com/kundajelab/chrombpnet/issues/81#issuecomment-1412384087

Something going wrong while generating the bigwig file....

**Comment by sid5427** [comment]
> Hey @sid5427
> 
> (1) Will look at the bams you sent over today.
> 
> (2) Just fixed a typo that should fix the modisco_motifs command error - this test version should have it -
> 
> `python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ chrombpnet==0.2.14`
> 
> I am going to see if anything needs to be changed inorder to make things work for your bam files and then merge these changes in the main repo. Will keep you posted.
> 
> (3) oh yeah! So we have test version of those scripts - using modisco motifs to annotate the motif coordinates. We have found that the motif coordinates are super set of footprint coordinates. Let me circle back with Anshul on releasing this, I might make it available through a beta testing version of the repo if that interests you.

For (3) - Yes please - we are hoping to find high confidence motifs for enhances and promoters for our study and this would help greatly.

**Comment by panushri25** [comment]
Closing this because this error has been resolved. @sid5427 as we discussed the bigwig generation is a system error rather than the repo dependency. But if you continue to see that error follow up on the email or a open a new issue.
