### ISSUE TITLE
reads_to_bigwig fails when fragments contain reads from chromosomes not in fasta

### ISSUE THREAD

**Issue by riyavsinha** [kundajelab/chrombpnet#86]
**Description**
When running `reads_to_bigwig.py`, fragments with reads not in the reference fasta cause the process to fail.

```
Traceback (most recent call last):
  File "/software/miniconda3/envs/r-chrombpnet2/lib/python3.8/site-packages/pyfaidx/__init__.py", line 1027, in __getitem__
    return self.records[rname]
KeyError: 'KI270713.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dir/chrombpnet/chrombpnet/helpers/preprocessing/reads_to_bigwig.py", line 100, in <module>
    main(args)
  File "dir/chrombpnet/chrombpnet/helpers/preprocessing/reads_to_bigwig.py", line 70, in main
    plus_shift, minus_shift = auto_shift_detect.compute_shift(args.input_bam_file,
  File "/software/miniconda3/envs/r-chrombpnet2/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/auto_shift_detect.py", line 198, in compute_shift
    plus_pwm, minus_pwm = get_pwms(sampled_plus_reads, sampled_minus_reads, genome_fasta_path)
  File "/software/miniconda3/envs/r-chrombpnet2/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/auto_shift_detect.py", line 95, in get_pwms
    cur = str(g[x['chr']][int(x['start'])-20:int(x['start'])+20])
  File "/software/miniconda3/envs/r-chrombpnet2/lib/python3.8/site-packages/pyfaidx/__init__.py", line 1029, in __getitem__
    raise KeyError("{0} not in {1}.".format(rname, self.filename))
KeyError: 'KI270713.1 not in dir/refs/hg38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.'
```

**Desired Behavior**
Have a warning for genes not found in reference chrom regions, but still continue to output for genes that do match. This is helpful for if data is from collaborators and we only care about parts that match, even if the data may contain small outliers.

Alternatively, maybe keep error as the default behavior, but have an option to do the above?

**Comment by panushri25** [comment]
Hey @riyavsinha , thank you for opening this issue. 

 I feel like users should be aware of what chromosomes they are including versus not maybe. Assuming an extreme case where users provide the wrong fasta file for the fragment file - which will result in  an empty output downstream. So this kind of error is useful. 

User can always check that the chromosomes in the fragment files match that of the `chrom.sizes` file right and then exclude reads accordingly?

**Comment by suragnair** [comment]
@panushri25 would it be useful to make the error more descriptive so people know exactly what the issue is?

**Comment by soumyakundu** [comment]
I think the more extreme cases, for example where all chromosomes are different, can be explicitly checked, and they can raise an error if they fail, as that indicates a systematic mismatch between files. For most other cases, for example, when your fragment files have a set of non-canonical chromosomes which have different names from the ones in the FASTA file, a warning should be sufficient. Otherwise, for these cases, which will likely make up the majority of the instances where users run into this issue, it will require each individual user to implement themselves the same filtering code that we can implement here to check on their behalf.

**Comment by akundaje** [comment]
I agree. I think this should raise a warning and automatic subsetting
should happen.

**Comment by panushri25** [comment]
I think users hardly check warnings. But if you think this is useful,  and @soumyakundu or @riyavsinha  if you already  have a filtering module, can you open a PR? I can see if it makes sense to integrate it in or atleast link to it in the documentation or FAQ.

**Comment by akundaje** [comment]
This is not an urgent issue to address. But we should address it.

**Comment by akundaje** [comment]
They dont need to check the warnings unless something looks off. Automatic
coordinate subsetting is quite standard for most tools in genomics.

A PR is a good idea. Reduces work for the primary developer. Also this
issue is not urgent so does not need to be addressed immediately. But would
suggest adding it to the next release.

**Comment by riyavsinha** [comment]
Definitely, I'd be happy to take this on if we can align on a general organization for the implementation here @panushri25 !

Would an appropriate addition be like adding a new file/module within the `preprocessing` directory, and then having `auto_shift_detect.py` call that within `compute_shift`[1](https://github.com/kundajelab/chrombpnet/blob/master/chrombpnet/helpers/preprocessing/auto_shift_detect.py#L194)?

**Comment by suragnair** [comment]
In the `auto_shift_detect.py` file, there are 3 functions that stream the 3 different file formats. The streamed files have the same format (tagAlign). The first place to check would be after they are first streamed-- this is done prior to sampling a few lines which are then used to estimate the tn5 bias. That's here:
https://github.com/kundajelab/chrombpnet/blob/1ea660fef2644b55f418e1a1f05823a0836922e5/chrombpnet/helpers/preprocessing/auto_shift_detect.py#L66-L74

You can add the warnings etc here.

The next step is when the files are streamed again to convert them to bigwig. That happens here:
https://github.com/kundajelab/chrombpnet/blob/1ea660fef2644b55f418e1a1f05823a0836922e5/chrombpnet/helpers/preprocessing/reads_to_bigwig.py#L30-L38

No need to warn here, just filter them. To keep it consistent with the overall style, it would be best to use `subprocess` to call a unix command such as grep to do the filtering. Note that `bedGraphToBigWig` will throw and error if there are lines in the stream that are not in the chrom.sizes file.

If you can make an initial attempt, I can refine it.

**Comment by suragnair** [comment]
This error can come up again at a later stage if there are peaks called on chromosomes that are not in the genome. @panushri25 is this handled separately elsewhere?

**Comment by akundaje** [comment]
I general I would recommend handling everything in Python rather than grep
etc. It introduces additional dependencies.

**Comment by suragnair** [comment]
That should be doable. The main requirement is that it works in a streaming fashion and doesn't load the whole file into memory.

**Comment by akundaje** [comment]
For sure. Can definitely stream to and from python.

**Comment by panushri25** [comment]
@suragnair So currently I am asking users to explicitly provide the train, test and validation chromosomes in an input file. So as long as they provide this correctly the peaks are appropriately subsetted to the appropriate chromosomes and there will no error. 

See example - https://github.com/kundajelab/chrombpnet/wiki/Preprocessing#define-train-validation-and-test-chromosome-splits
