### ISSUE TITLE
wrapper for preprocessing

### ISSUE THREAD

**Issue by zji90** [kundajelab/chrombpnet#89]
Hi,

It seems that defining folds and background regions are quite automatic once there is bam and called peaks as inputs. Is there a wrapper that automatically deals with fold and background?

**Comment by panushri25** [comment]
Hi @zji90 Are you referring to the `chrombpnet prep splits` (https://github.com/kundajelab/chrombpnet/wiki/Preprocessing#define-train-validation-and-test-chromosome-splits) and `chrombpnet prep nonpeaks` (https://github.com/kundajelab/chrombpnet/wiki/Preprocessing#generate-non-peaks-background-regions) wrappers provided with the tutorial?

**Comment by zji90** [comment]
Yes, is it possible to integrate them into the main chrombpnet call so that I don't need to call chrombpnet prep splits and chrombpnet prep nonpeaks separately? A wrapper in my mind will have a single command but call the two chrombpnet prep before running the main chrombpnet.

**Comment by panushri25** [comment]
yeah correct. I intentionally kept these 2 choices independent of the whole pipeline to allow some flexibility and transparency. Will think and discuss more about this.

Thank you for the suggestion!

**Comment by panushri25** [comment]
Added this for future tools dev - https://github.com/kundajelab/chrombpnet/wiki/Software-dev
