### ISSUE TITLE
pretrained model forbidden

### ISSUE THREAD

**Issue by zji90** [kundajelab/chrombpnet#90]
Hi,

When I try to download the models on https://mitra.stanford.edu/kundaje/oak/akundaje/anusri/chrombpnet_data/input_files/bias_models/ 

It says 403 forbidden. Is there a way to fix this? Thanks!

**Comment by panushri25** [comment]
Yes sorry about that, the server needed a remount to fix the html link. Will ping here when it is fixed

**Comment by akundaje** [comment]
Anusri - I suggest you upload these to Zenodo and add the permanent DOI
rather than using mitra links

-Anshul.

**Comment by panushri25** [comment]
Good idea, let me do that

**Comment by zji90** [comment]
I am able to access the server. Can you provide more descriptions of which pretrained model I should use for human and mouse? Currently there are two models ENCSR868FGK_bias_fold_0.h5 and scATAC_dermal_fibroblast.h5.

**Comment by akundaje** [comment]
One thing is to make sure you use the exact fold structure that we use for
the bulk data. Anu - is this set in the default.

Also Anu - can you share the 5 fold bias models in human and mouse that
work best for scATAC.

Jason - I suggest you first try this on 5 datasets and then we can check
the diagnostics to see if these default bias tracks do sufficient
correction. Then proceed to others.

Anshul

**Comment by panushri25** [comment]
All the human folds are provided with the repo already - reposting the link - https://mitra.stanford.edu/kundaje/oak/akundaje/anusri/chrombpnet_data/input_files/folds/

Will add the mouse folds and the bias models as well to the list.

**Comment by panushri25** [comment]
@zji90 I have seen this model `ENCSR868FGK_bias_fold_0.h5 ` generally work well for most models. This is trained on fold 0 - I will add the remaining 5-fold models to the repository

**Comment by zji90** [comment]
Please correct me if I am wrong:

For human I should use: 
for '-b' argument, ENCSR868FGK_bias_fold_0.h5    (downloaded from https://mitra.stanford.edu/kundaje/oak/akundaje/anusri/chrombpnet_data/input_files/bias_models/ATAC/)
for '-fl' argument, fold_0.json    (downloaded from https://mitra.stanford.edu/kundaje/oak/akundaje/anusri/chrombpnet_data/input_files/folds/)

For mouse wait for new models and folds to be posted.

Another question is that if you have five models for five folds, shall I just use fold_0 and ignore the other four?

**Comment by akundaje** [comment]
You should match bias model folds to the training fold. So if right now you
are just training fold0 then only use fold0 bias model. This is to make
sure that the bias model and ChromBPNet have both not seen the validation
and test sets for each fold.

I'll let Anusri answer the other question.

**Comment by zji90** [comment]
Oh I thought we are using pretrained model instead of training by myself?

Is it possible to make README more informative so it's easier to follow what exactly I should do? It would be extremely helpful if step-by-step instructions can be given (e.g., where to download what model to use for what argument)

**Comment by akundaje** [comment]
You are not training the bias model. You are using a Pretrained bias model
but the bias model should be Pretrained on the same fold as the ChromBPNet
model you are planning to use it with. This is why you need to match folds
of the pretrained bias model and the folds you are training ChromBPNet on.

**Comment by akundaje** [comment]
I thought the instructions are very clear but maybe it's not clear enough
for using Pretrained bias models.

Anusri - can you try to make it clearer for using Pretrained bias models
and fold matching.

Anshul

**Comment by akundaje** [comment]
I suggest you have a call with Anusri to clarify things and then we can
improve the documentation to address your doubts

Anshul

**Comment by zji90** [comment]
OK I will contact Anu thanks!
