### ISSUE TITLE
counts threshold is 0 - all non peaks will be filtered!

### ISSUE THREAD

**Issue by monikaheinzl** [kundajelab/chrombpnet#91]
Hi,

I'm trying to run ChromBPnet for my ATAC-seq data and preprocessed my data in the same way as your test data. But when I want to train the bias model, I'm getting the following error:

```
Number of non peaks input:  11100
Number of non peaks filtered because the input/output is on the edge:  0
Number of non peaks being used:  11100
Number of non peaks input:  1300
Number of non peaks filtered because the input/output is on the edge:  0
Number of non peaks being used:  1300
Number of peaks input:  11275
Number of peaks filtered because the input/output is on the edge:  5725
Number of peaks being used:  5550
Traceback (most recent call last):
  File "/.local/bin/chrombpnet", line 8, in <module>
     sys.exit(main())
  File "/.local/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 38, in main
     pipelines.train_bias_pipeline(args)
  File "/.local/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 290, in train_bias_pipeline
     find_bias_hyperparams.main(args_copy)
  File "/.local/lib/python3.8/site-packages/chrombpnet/helpers/hyperparameters/find_bias_hyperparams.py", line 81, in main
     assert(counts_threshold > 0) # counts threshold is 0 - all non peaks will be filtered!
AssertionError
```

I couldn't find any description of this error in the FAQs, so it would be great if you could provide me with some information on how I can fix this issue. Many thanks!

Best,
Monika

**Comment by monikaheinzl** [comment]
I already could solve it. I had an issue with my input bed file.

**Comment by panushri25** [comment]
Glad you figured it out. The number of peaks you are inputing seems quite low though. Are you doing a test run?

We generally have about 100K peaks + for our samples

**Comment by zixiaowang17** [comment]
> I already could solve it. I had an issue with my input bed file.

Hi！ May I know what issue you figured out finally, please? I also got this error when using pred_bw. Thanks!
