### ISSUE TITLE
Predicted counts over bed regions

### ISSUE THREAD

**Issue by snaqvi1990** [kundajelab/chrombpnet#94]
Hello,

Is there a way with the existing pipeline to output predicted and observed counts over a set of genomic regions - this is exactly what seems to be happening under the hood when generating the evaluation plots (i.e. chrombpnet_only_peaks.counts_pearsonr.png), but I'm not sure how to extract that explicitly.

Thanks,
Sahin

**Comment by panushri25** [comment]
Hello Sahin,

You can use this script here by inputting the observed data - https://github.com/kundajelab/chrombpnet/wiki/Generate-prediction-bigwigs

Thanks,
Anu

**Comment by snaqvi1990** [comment]
Hi Anusri,

I know I closed this but I just had one more questions. Are the predicted bigwigs outputted showing counts on a log scale?

Thanks,
Sahin

**Comment by panushri25** [comment]
No its the normal counts scale
