### ISSUE TITLE
Chrombpnet train not using gpu?

### ISSUE THREAD

**Issue by snaqvi1990** [kundajelab/chrombpnet#95]
Hello,

I was able to successfully run chrombpnet pipeline on ATAC data. However, it seems to be much slower than before -- with the pre-release version of chrombpnet, I was able to train a model in ~24 hours using Stanford sherlock GPUs. Now, chrombpnet only gets through 2 epochs by ~24 hours. I am using the same exact gpu specifications as with the pre-release version, with cudnn 8.1.1.33 and cuda 12.0.0. Any idea what could be going on?

Thanks,
Sahin

**Comment by panushri25** [comment]
Hello Sahin,

We did update the tensorflow version for 2.4 to 2.8, and I think 2.8 requires a cudnn version of 11.2.

**Comment by panushri25** [comment]
@annashcherbina Can you comment on this?

**Comment by annashch-insitro** [comment]
Hi Sahin, it seems like the code is running on CPU rather than GPU. 
Please uninstall tensorflow, specify cudnn=8.1, cuda=11.2, TensorRT >=7.2.2 in your LD_LIBRARY_PATH 
Then pip install tensorflow-gpu==2.8

**Comment by panushri25** [comment]
@snaqvi1990 Another option is to use the docker image with singularity on sherlock

**Comment by snaqvi1990** [comment]
Thank you! Will give it a try. A bit unrelated, but is there any way to get chrombpnet pipeline to use the existing .bw file generated from a previous run rather than re-do the preprocessing?

**Comment by panushri25** [comment]
That feature is currently not enabled, we didn't want the users to worry about or make errors in doing shift and building bigwigs.

**Comment by snaqvi1990** [comment]
The model trains on GPUs now (very quickly). Thanks!
