### ISSUE TITLE
Chrombpnet training error through 'chrombpnet pipeline' using pre-trained bias model

### ISSUE THREAD

**Issue by XuanrZhang** [kundajelab/chrombpnet#96]
Hi @ panushri25,

Thanks for the model development.

I am interested in chrombpnet, and I followed the tutorial to train the chrombpnet model with provided test data and pre-trained bia model. 

I got the below error, when I run chrombpnet pipeline, refer to [training step](https://github.com/kundajelab/chrombpnet/wiki/ChromBPNet-training).  I am more sure whether some wrong with the code.

![WX20230406-150653](https://user-images.githubusercontent.com/18049816/230276926-0098dad1-43c4-4712-badb-8a93ef182dad.png) 

I appreciate any help you can provide.

Best,
Xuan

**Comment by panushri25** [comment]
Hello,

What installation procedure did you follow for using chrombpnet?

It looks like are unable to use the `bedGraphToBIgwig` command? Did you do the following step of the installation - `conda install -y -c conda-forge -c bioconda samtools bedtools ucsc-bedgraphtobigwig pybigwig meme`

**Comment by XuanrZhang** [comment]
> Hello,
> 
> What installation procedure did you follow for using chrombpnet?
> 
> It looks like are unable to use the `bedGraphToBIgwig` command? Did you do the following step of the installation - `conda install -y -c conda-forge -c bioconda samtools bedtools ucsc-bedgraphtobigwig pybigwig meme`

Hi @panushri25 ,

Thanks for your quick reply. 
I didn't installed 'bedgraphtobigwig' successfully before. I reinstalled it and the error fixed.

But I got another error here. What's header content required? 
  
![image](https://user-images.githubusercontent.com/18049816/230520013-2303420b-e84e-4e91-a469-3a9060cb0eb7.png)

Thanks in advance!

**Comment by panushri25** [comment]
The error says needLargeMem - so I think there is not enough memory for the job

**Comment by XuanrZhang** [comment]
> The error says needLargeMem - so I think there is not enough memory for the job

Thanks for the reply. It works now.

**Comment by panushri25** [comment]
Thank for confirming. I will close the issue for now, feel free to open it if anything else comes up.
