### ISSUE TITLE
Predicting effects of perturbations

### ISSUE THREAD

**Issue by snaqvi1990** [kundajelab/chrombpnet#99]
Hi, 

This is more of a science question, so apologies if this is not the appropriate venue. I am just wondering if you guys have used ChromBPNet to predict the effect of perturbations on ATAC (i.e. what is the accessibility profile at a given region in wild-type vs cells in which a TF has been knocked out). I have ATAC-seq from the same cell type where I have perturbed a TF to various degrees and am trying to predict those TF-dependent changes from sequence. Currently I am running a separate ChromBPNet model for each perturbation dataset (all replicates combined), and then summing up predicted counts over test regions for each model separately and looking at the fold change between models. It is not working particularly well because this is not what ChromBPNet is trying to do by default. I realize that this is probably not something that is immediately in the pipeline but would appreciate any thoughts you guys may have.

Thanks!
Sahin

**Comment by akundaje** [comment]
We should discuss this in more detail. It can definitely be done. We've
done this for RBP knockouts using RNA readouts. Can definitely be done for
ATAC after TF knockout but will require some tweaks/normalizations etc.
We're building these kinds of differential model comparisons. Not done yet
but will be happy to discuss and collaborate.

**Comment by snaqvi1990** [comment]
Sounds good, thanks Anshul!
